window.LA_SETTINGS = {
  campaign: {
    name: 'Leads Frios — Google Ads',
    mono: 'LF',
    id: 37,
    status: 'paused',
    channel: 'WhatsApp',
    dailyLimit: '0 / 100',
    activeHours: '09:00 – 19:00',
    owner: 'Energia Solar Catarinense',
    ownerInit: 'ES',
  },
  business: {
    companyName: 'Energia Solar Catarinense',
    agentName: 'Ana',
    businessDescription: 'Leads que demonstraram interesse em energia solar mas não converteram. Reativação via WhatsApp com IA.',
    knowledgeBase: '',
  },
  ai: {
    firstMessage: 'Oi [Nome]! 😊 Aqui é a Ana da Energia Solar Catarinense. Há um tempo você demonstrou interesse em energia solar — tudo bem por aí?',
    aiRole: '',
    aiVoiceMode: 'Off',
    linkedPrompt: '',
    bumps: [
      { delay: 24, message: '' },
      { delay: 24, message: '' },
      { delay: 48, message: '' },
      { delay: 72, message: '' },
    ],
  },
  behavior: {
    language: 'Portuguese',
    niche: '',
    website: 'https://example.com',
    calendarLink: 'https://calendly.com/...',
    demoCampaign: false,
    account: 41,
    status: 'Paused',
    type: '',
    bookingMode: 'Call Agent',
    typosPerChat: 1,
    activeHoursStart: '09:00:00',
    activeHoursEnd: '19:00:00',
  },
};
