// Shared types for the Lead detail panel sections. Extracted verbatim from
// LeadDetailPanel.tsx (structural split — no behaviour change).

export interface Interaction {
  id: number;
  lead_id?: number;
  Leads_id?: number;
  direction: string;
  /** DB column is uppercase "Content" — API returns this form */
  Content?: string;
  /** fallback lowercase form */
  content?: string;
  created_at?: string;
  type?: string;
  /** DB column is uppercase "Who" — AI agent name or sender identifier */
  Who?: string;
  who?: string;
  /** true when the message was generated by AI */
  ai_generated?: boolean;
  /** true when a human agent manually sent this message */
  is_manual_follow_up?: boolean;
  is_bump?: boolean;
  triggered_by?: string;
  status?: string;
  sentiment_detected?: string;
}

export interface TagData {
  id: number;
  name: string;
  color?: string | null;
  category?: string | null;
  slug?: string | null;
}

export interface LeadTagEntry {
  id?: number;
  tagsId?: number;
  Tags_id?: number;
  leadsId?: number;
  Leads_id?: number;
  tagName?: string | null;
}
