#!/usr/bin/env python3
"""Build the Dutch homepage (leadawaker.com/nl) from the English one.

    python3 script/build-site-nl.py

Same mechanics as build-site-pt.py (see script/site_lang.py): index.html stays
the single source, this file holds the Dutch copy, adapted rather than
translated word for word. Every English string must still exist, so an edit to
the English page fails loudly here instead of leaving English on /nl.

Not translated on purpose: the hero call (recording, transcript, Northgate
Motors). Gabriel is recording a Dutch one. The radiator WhatsApp example stays:
it fits the Dutch market as is.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from site_lang import ANY, build, common_pairs  # noqa: E402

# Widget_Configs row 8: same Sara and look as row 6, language nl, Dutch greeting.
WIDGET_KEY_EN = "wk_pNUlirtOPVBVkViwqXgsZmFq"
WIDGET_KEY_NL = "wk_KXOIfpmMfShAKcLjinezibMs"

# (english, dutch) or (english, dutch, count)
PAIRS = common_pairs("nl", "/nl") + [
    ('<html lang="en">',
     '<html lang="nl">'),
    ("Lead Awaker: the AI receptionist that picks up when you can't",
     'Lead Awaker: de AI-receptioniste die opneemt als jij het niet kunt', 2),
    ('Sara answers your phone, website chat and WhatsApp day and night, and books customers straight into your calendar.',
     'Sara beantwoordt je telefoon, websitechat en WhatsApp, dag en nacht, en plant klanten direct in je agenda.', 2),
    ('<meta property="og:url" content="https://www.leadawaker.com/nl">', '<meta property="og:url" content="https://www.leadawaker.com/nl">\n<meta property="og:locale" content="nl_NL">'),
    ('<nav class="nav" aria-label="Main">',
     '<nav class="nav" aria-label="Hoofdmenu">'),
    ('<a href="#phone">Phone</a>',
     '<a href="#phone">Telefoon</a>', 2),
    ('<a href="#website">Website</a>',
     '<a href="#website">Website</a>'),
    ('<a href="#how">How it works</a>',
     '<a href="#how">Zo werkt het</a>'),
    ('<a href="/reactivate">Old leads</a>',
     '<a href="/reactivate">Oude leads</a>'),
    ('href="/login">Log in</a>',
     'href="/login">Inloggen</a>', 2),
    ('rel="noopener">Book a demo</a>',
     'rel="noopener">Demo plannen</a>'),
    ('aria-label="Open menu"',
     'aria-label="Menu openen"'),
    ('<a href="#website">Website chat</a>',
     '<a href="#website">Websitechat</a>'),
    ('<a href="#calendar">Calendar booking</a>',
     '<a href="#calendar">Afspraken inplannen</a>'),
    ('<a href="#faq">Questions</a>',
     '<a href="#faq">Vragen</a>'),
    ('<a href="/reactivate">Database reactivation</a>',
     '<a href="/reactivate">Database-reactivatie</a>', 2),
    ('<i></i>AI receptionist for busy businesses</span>',
     '<i></i>AI-receptioniste voor drukke ondernemers</span>'),
    ('<h1>The receptionist who picks up when <em class="w">you can’t</em></h1>',
     '<h1>De receptioniste die opneemt als <em class="w">jij het niet kunt</em></h1>'),
    ('Sara is your multichannel receptionist. She answers day and night and books straight into your calendar.',
     'Sara neemt je telefoon, WhatsApp en websitechat aan. Dag en nacht, en ze plant direct in je agenda.'),
    ('rel="noopener">Test her out</a>',
     'rel="noopener">Probeer Sara uit</a>'),
    ('href="#phone">See a day of calls</a>',
     'href="#phone">Bekijk een dag vol gesprekken</a>'),
    ('<span>1</span>Rings</li>',
     '<span>1</span>Gaat over</li>'),
    ('<span>2</span>Qualifies</li>',
     '<span>2</span>Vraagt door</li>'),
    ('<span>3</span>Books</li>',
     '<span>3</span>Plant in</li>'),
    ('<span>4</span>Tells you</li>',
     '<span>4</span>Meldt het</li>'),
    ('id="sc-status">Incoming call</span>',
     'id="sc-status">Inkomend gesprek</span>'),
    ('<small>Answered by Sara</small>',
     '<small>Aangenomen door Sara</small>'),
    ('aria-label="Play the example call"',
     'aria-label="Voorbeeldgesprek afspelen"'),
    ('id="play-l">Play the call</span>',
     'id="play-l">Gesprek afspelen</span>'),
    ('Press play to hear Sara take a call from a buyer, after the showroom has closed.',
     'Druk op play en hoor hoe Sara een koper te woord staat, als de showroom al dicht is.'),
    ('aria-label="Pause the call"',
     'aria-label="Gesprek pauzeren"'),
    ('Live transcript <small>',
     'Live transcript <small>'),
    ('<small>New lead · phone call at 19:42</small>',
     '<small>Nieuwe lead · gebeld om 19:42</small>'),
    ('<span class="chip g">Booked</span>',
     '<span class="chip g">Ingepland</span>', 2),
    ('<small>Recap from Sara</small>',
     '<small>Samenvatting van Sara</small>'),
    ('<p>Asked about the 2023 Porsche Cayenne Coupé E-Hybrid, for family trips. Saw a cheaper one elsewhere, with three times the mileage.</p>',
     '<p>Vroeg naar de Porsche Cayenne Coupé E-Hybrid uit 2023, voor gezinsritten. Zag elders een goedkopere, met drie keer zoveel kilometers.</p>'),
    ('aria-label="Play the recording"',
     'aria-label="Opname afspelen"'),
    ('<b>Tom’s calendar</b><small>Next week</small>',
     '<b>Agenda van Tom</b><small>Volgende week</small>'),
    ('<span class="d">Mon</span><span class="d">Tue</span><span class="d">Wed</span><span class="d">Thu</span><span class="d">Fri</span><span class="d sat">Sat</span>',
     '<span class="d">Ma</span><span class="d">Di</span><span class="d">Wo</span><span class="d">Do</span><span class="d">Vr</span><span class="d sat">Za</span>'),
    ('<small>Tuesday</small><b class="num">19:43</b>',
     '<small>Dinsdag</small><b class="num">19:43</b>'),
    ('<time>now</time>',
     '<time>nu</time>'),
    ('<span class="u">Booked</span> Gabriel, test drive Monday 15:00, 2023 Porsche Cayenne Coupé E-Hybrid. For family trips. Saw a cheaper one elsewhere, with three times the mileage.',
     '<span class="u">Ingepland</span> Gabriel, proefrit maandag 15:00, Porsche Cayenne Coupé E-Hybrid uit 2023. Voor gezinsritten. Zag elders een goedkopere, met drie keer zoveel kilometers.'),
    ('just now',
     'zojuist'),
    ('<small>New lead · call at 19:42</small>',
     '<small>Nieuwe lead · gebeld om 19:42</small>'),
    ('<small>Mon</small><b class="num">15:00</b>',
     '<small>Ma</small><b class="num">15:00</b>'),
    ('<span>Added to Tom’s calendar</span>',
     '<span>In de agenda van Tom</span>'),
    ('<span class="own-l">Your phone</span>',
     '<span class="own-l">Jouw telefoon</span>'),
    ('id="again" type="button">Play the call again</button>',
     'id="again" type="button">Gesprek opnieuw afspelen</button>'),
    ('<h2>Four ways to answer the phone</h2><p>Plenty of callers don’t leave a message. They ring the next business on the list.</p>',
     '<h2>Vier manieren om de telefoon op te nemen</h2><p>Veel bellers spreken niets in. Ze bellen gewoon de volgende op de lijst.</p>'),
    ('aria-label="Comparison of four ways to handle calls, with what the caller hears"',
     'aria-label="Vergelijking van vier manieren om gesprekken aan te nemen, met wat de beller hoort"'),
    ('<b>You</b></span>',
     '<b>Jij</b></span>'),
    ('<b>Voicemail</b></span>',
     '<b>Voicemail</b></span>'),
    ('<b>A service</b></span>',
     '<b>Een belservice</b></span>'),
    ('<span>Yes</span>',
     '<span>Ja</span>', ANY),
    ('<span>No</span>',
     '<span>Nee</span>', ANY),
    ('<span>Sometimes</span>',
     '<span>Soms</span>', 2),
    ('<span>Message</span><small>',
     '<span>Bericht</span><small>'),
    ('rowheader">Answers every call<',
     'rowheader">Neemt altijd op<'),
    ('<small>Rings out while you work</small>',
     '<small>Gaat over terwijl je werkt</small>'),
    ('<small>“Leave a message”</small>',
     '<small>“Spreek een bericht in”</small>'),
    ('<small>“How can I help?”</small>',
     '<small>“Waarmee kan ik helpen?”</small>'),
    ('<small>“Northgate, Sara speaking”</small>',
     '<small>“Northgate, met Sara”</small>'),
    ('rowheader">Knows your business<',
     'rowheader">Kent je bedrijf<'),
    ('<small>You know it all</small>',
     '<small>Jij weet alles</small>'),
    ('<small>Says nothing</small>',
     '<small>Zegt niets</small>'),
    ('<small>“I’ll pass it on”</small>',
     '<small>“Ik geef het door”</small>'),
    ('<small>“The Cayenne? We’ve got one”</small>',
     '<small>“De Cayenne? Die hebben we”</small>'),
    ('rowheader">Books into your calendar<',
     'rowheader">Plant in je agenda<'),
    ('<small>“Let me call you back”</small>',
     '<small>“Ik bel je terug”</small>'),
    ('<small>Nobody books</small>',
     '<small>Niemand plant in</small>'),
    ('<small>“Someone will call you”</small>',
     '<small>“Er belt iemand terug”</small>'),
    ('<small>“Monday at 3, booked”</small>',
     '<small>“Maandag 15:00, staat erin”</small>'),
    ('rowheader">Instant reply on chat and WhatsApp<',
     'rowheader">Direct antwoord in chat en WhatsApp<'),
    ('<small>When you see it</small>',
     '<small>Als je het ziet</small>'),
    ('<small>Phone only</small>',
     '<small>Alleen telefoon</small>', 2),
    ('<small>In seconds</small>',
     '<small>Binnen seconden</small>'),
    ('rowheader">Leaves you free to work<',
     'rowheader">Laat jou ongestoord werken<'),
    ('<small>You stop what you’re doing</small>',
     '<small>Je legt je werk neer</small>'),
    ('<small>But you lose them</small>',
     '<small>Maar je verliest ze</small>'),
    ('<small>For a fee per minute</small>',
     '<small>Tegen een tarief per minuut</small>'),
    ('<small>You get a recap</small>',
     '<small>En je krijgt een samenvatting</small>'),
    ('rowheader">Costs you<',
     'rowheader">Kost je<'),
    ('role="cell">Your time<',
     'role="cell">Je tijd<'),
    ('role="cell">Customers<',
     'role="cell">Klanten<'),
    ('role="cell">Per minute<',
     'role="cell">Per minuut<'),
    ('class="em">Fixed fee<',
     'class="em">Vast bedrag<'),
    ('aria-expanded="false">Show what the caller hears</button>',
     'aria-expanded="false">Laat horen wat de beller hoort</button>'),
    ('alt="A craftsman in his workshop, checking a message on his phone"',
     'alt="Een vakman in zijn werkplaats die een bericht op zijn telefoon leest"'),
    ('<h2>Busy hands.<br><em class="w">Nothing missed.</em></h2><p>You build, fix and serve. Sara takes the calls.</p>',
     '<h2>Handen vol.<br><em class="w">Niets gemist.</em></h2><p>Jij bouwt, repareert en helpt klanten. Sara neemt de telefoon.</p>'),
    ('<b>Sara · while you were in the workshop</b><span>2 quotes requested · 1 visit booked</span>',
     '<b>Sara · terwijl jij in de werkplaats stond</b><span>2 offertes aangevraagd · 1 bezoek ingepland</span>'),
    ('<h2>One receptionist, <em class="w">three front doors</em></h2>',
     '<h2>Eén receptioniste, <em class="w">drie voordeuren</em></h2>'),
    ('<h3>You choose where she answers</h3>',
     '<h3>Jij kiest waar ze opneemt</h3>'),
    ('id="hub-sum">Sara answers your <b>phone, WhatsApp and website chat</b></p>',
     'id="hub-sum">Sara beantwoordt <b>je telefoon, WhatsApp en websitechat</b></p>'),
    ('<b>Phone</b><small>Answers your calls</small>',
     '<b>Telefoon</b><small>Neemt je gesprekken aan</small>'),
    ('<b>WhatsApp</b><small>Answers messages</small>',
     '<b>WhatsApp</b><small>Beantwoordt berichten</small>'),
    ('<b>Website chat</b><small>Answers visitors</small>',
     '<b>Websitechat</b><small>Helpt bezoekers</small>'),
    ('</i>On the phone <span class="offtag">Switched off</span>',
     '</i>Aan de telefoon <span class="offtag">Uitgeschakeld</span>'),
    ('<h3>You answer when you can. She answers when you can’t.</h3>',
     '<h3>Jij neemt op als het kan. Zij neemt op als het niet kan.</h3>'),
    ('Missed calls roll over to Sara. She books the appointment, or a callback if you prefer.',
     'Gemiste oproepen gaan door naar Sara. Zij plant de afspraak in, of een terugbelmoment als je dat liever hebt.'),
    ('aria-label="A phone lock screen running through a Tuesday from 06:00 to 23:00. While the owner is busy with test drives, customers or a closed showroom, Sara answers the calls and books test drives, viewings and valuations."',
     'aria-label="Een telefoon-vergrendelscherm dat een dinsdag doorloopt van 06:00 tot 23:00. Terwijl de eigenaar op proefrit is, bij een klant zit of de showroom dicht is, neemt Sara de gesprekken aan en plant ze proefritten, bezichtigingen en taxaties in."'),
    ('<small>Tuesday</small><b class="num" id="lp-time">',
     '<small>Dinsdag</small><b class="num" id="lp-time">'),
    ('id="lp-st">Showroom closed</span>',
     'id="lp-st">Showroom dicht</span>'),
    ('<li>On a test drive</li><li>With a customer</li><li>After hours</li><li>Your recap</li>',
     '<li>Op proefrit</li><li>Bij een klant</li><li>Na sluitingstijd</li><li>Jouw overzicht</li>'),
    ('</i>On WhatsApp <span class="offtag">Switched off</span>',
     '</i>Op WhatsApp <span class="offtag">Uitgeschakeld</span>'),
    ('<h3>Immediate replies where your customers already are</h3>',
     '<h3>Direct antwoord, waar je klanten al zitten</h3>'),
    ('Customers send a photo, a voice note or a question. Sara replies and books them in.',
     'Klanten sturen een foto, een spraakbericht of een vraag. Sara antwoordt en plant ze in.'),
    ('aria-label="Illustration: a WhatsApp chat with a plumber. A customer sends a photo of a radiator that stays cold at the top, the assistant explains it is a quick job and books a visit at the end of the day."',
     'aria-label="Illustratie: een WhatsApp-gesprek met een loodgieter. Een klant stuurt een foto van een radiator die bovenin koud blijft, de assistent legt uit dat het een klein klusje is en plant een bezoek aan het eind van de dag."'),
    ('Hartley Plumbing',
     'Installatiebedrijf De Wit'),
    ('Business account',
     'Zakelijk account'),
    ('Hi, this radiator stays cold at the top. Not urgent, but could someone take a look?',
     'Hoi, deze radiator blijft bovenin koud. Geen haast, maar kan iemand er even naar kijken?'),
    ('Thanks for the photo. It probably just needs bleeding. Mike can check it at the end of his day.',
     'Bedankt voor de foto. Waarschijnlijk moet hij even ontlucht worden. Bas kan aan het eind van zijn dag langskomen.'),
    ('Does today at 17:30 or tomorrow at 17:00 suit you?',
     'Past vandaag om 17:30 of morgen om 17:00?'),
    ('<div class="wm me">Today works<sub>',
     '<div class="wm me">Vandaag is prima<sub>'),
    ('Done. Mike will be there today at 17:30. I’ll remind you an hour before.',
     'Top! Bas is er vandaag om 17:30. Ik stuur je een uur van tevoren een herinnering.'),
    ('</svg>Message<svg',
     '</svg>Bericht<svg'),
    ('<li>Sends a photo</li><li>Gets an answer</li><li>Chooses a slot</li><li>Booked</li>',
     '<li>Stuurt een foto</li><li>Krijgt antwoord</li><li>Kiest een tijd</li><li>Ingepland</li>'),
    ('data-replay="wa">Play the chat again</button>',
     'data-replay="wa">Chat opnieuw afspelen</button>'),
    ('</i>On your website <span class="offtag">Switched off</span>',
     '</i>Op je website <span class="offtag">Uitgeschakeld</span>'),
    ('<h3>Late-night visitors become booked appointments</h3>',
     '<h3>Nachtelijke bezoekers worden afspraken</h3>'),
    ('She answers from your site and books a free slot. Visitors can type, send a photo or leave a voice note.',
     'Ze helpt bezoekers op je site en plant een vrij moment in. Bezoekers kunnen typen, een foto sturen of een spraakbericht inspreken.'),
    ('<p><b>She wears your brand.</b> Pick her colour, her face and the button. Her chat bubbles follow.</p>',
     '<p><b>Ze draagt jouw huisstijl.</b> Kies haar kleur, haar gezicht en de knop. Haar chatballonnen kleuren mee.</p>'),
    ('id="look-kind">Metal</span> · <span id="look-name">Silver</span>',
     'id="look-kind">Metaal</span> · <span id="look-name">Zilver</span>'),
    ('data-kind="Metal"', 'data-kind="Metaal"', ANY),
    ('data-name="Silver rim"',
     'data-name="Zilveren rand"', ANY),
    ('data-name="Gold rim"',
     'data-name="Gouden rand"', ANY),
    ('data-name="Silver"',
     'data-name="Zilver"', ANY),
    ('data-name="Gold"',
     'data-name="Goud"', ANY),
    ('data-name="Rose gold"',
     'data-name="Roségoud"', ANY),
    ('data-name="Copper"',
     'data-name="Koper"', ANY),
    ('data-name="Cream"',
     'data-name="Crème"', ANY),
    ('data-name="Sage"',
     'data-name="Salie"', ANY),
    ('data-name="Sky"',
     'data-name="Hemelsblauw"', ANY),
    ('data-name="Violet"',
     'data-name="Violet"', ANY),
    ('data-name="Wine"',
     'data-name="Wijnrood"', ANY),
    ('data-kind="Chat button"',
     'data-kind="Chatknop"', ANY),
    ('data-kind="Colour swirl"',
     'data-kind="Kleurverloop"', ANY),
    ('aria-label="Illustration: a dental practice website at 23:04 with Sara in the practice\'s blue. The chat opens, the visitor taps Book an appointment, sends a voice note saying they are a new patient, and Sara books Saturday at 10:15."',
     'aria-label="Illustratie: de website van een tandartspraktijk om 23:04, met Sara in het blauw van de praktijk. De chat opent, de bezoeker tikt op Afspraak maken, stuurt een spraakbericht dat ze nieuwe patiënt is, en Sara plant zaterdag 10:15 in."'),
    ('brightsmiledental.com/new-patients',
     'tandartslindenhof.nl/nieuwe-patienten'),
    ('<b>New patients welcome</b>',
     '<b>Nieuwe patiënten welkom</b>'),
    ('Hi there! Have a question? Chat with me here.',
     'Hoi! Heb je een vraag? Chat hier met me.'),
    ('Digital assistant · Brightsmile Dental',
     'Digitale assistent · Tandartspraktijk Lindenhof'),
    ('Hi, I’m Sara from Brightsmile Dental. How can I help?',
     'Hoi, ik ben Sara van Tandartspraktijk Lindenhof. Waarmee kan ik je helpen?'),
    ('data-k="u1">Book an appointment</div>',
     'data-k="u1">Afspraak maken</div>'),
    ('Happy to help. Are you a new or an existing patient?',
     'Graag! Ben je al patiënt bij ons, of ben je nieuw?'),
    ('“New patient. I haven’t seen a dentist in a while. Anything this weekend?”',
     '“Nieuwe patiënt. Ik ben al een tijdje niet bij de tandarts geweest. Kan het dit weekend?”'),
    ('No problem at all. Your first visit is a check-up and a clean, about 45 minutes. Here are the next free times:',
     'Geen probleem. Je eerste bezoek is een controle met gebitsreiniging, zo’n 45 minuten. Dit zijn de eerstvolgende vrije tijden:'),
    ('<span>Fri 17:30</span><span class="pk">Sat 10:15</span><span>Sat 11:45</span>',
     '<span>Vr 17:30</span><span class="pk">Za 10:15</span><span>Za 11:45</span>'),
    ('<small>Booked</small><b>Sat 10:15 · New patient check-up</b>',
     '<small>Ingepland</small><b>Za 10:15 · Intake nieuwe patiënt</b>'),
    ('<span class="pk2">Book an appointment</span><span>Prices</span><span>Opening hours</span>',
     '<span class="pk2">Afspraak maken</span><span>Prijzen</span><span>Openingstijden</span>'),
    ('Type your message...',
     'Typ je bericht...'),
    ('23:04 · practice closed',
     '23:04 · praktijk gesloten'),
    ('<li>Opens the chat</li><li>Taps Book</li><li>Sends a voice note</li><li>Booked</li>',
     '<li>Opent de chat</li><li>Tikt op Afspraak</li><li>Stuurt een spraakbericht</li><li>Ingepland</li>'),
    ('data-replay="widget">Play the chat again</button>',
     'data-replay="widget">Chat opnieuw afspelen</button>'),
    ('<h2>You decide what she says</h2>',
     '<h2>Jij bepaalt wat ze zegt</h2>'),
    ('<p>She works from a detailed brief we build with you in your onboarding session.</p>',
     '<p>Ze werkt vanuit een uitgebreide briefing die we samen met je opstellen tijdens de onboarding.</p>'),
    ('aria-label="Sara shown as a speaking orb, with the points of her brief circling around her, coming towards you and moving away behind her."',
     'aria-label="Sara als sprekende bol, met de punten uit haar briefing die om haar heen draaien, naar je toe komen en achter haar langs verdwijnen."'),
    ('<span class="sv-sub">Phone · Website · WhatsApp</span>',
     '<span class="sv-sub">Telefoon · Website · WhatsApp</span>'),
    ('<h3>Nobody waits on hold</h3><p>She picks up straight away, every time.</p>',
     '<h3>Niemand hangt in de wacht</h3><p>Ze neemt direct op, elke keer.</p>'),
    ('<h3>She doesn’t guess</h3><p>Not in her brief? She takes a message.</p>',
     '<h3>Ze gokt niet</h3><p>Staat het niet in haar briefing? Dan noteert ze een bericht.</p>'),
    ('<h3>Unhappy callers go to you</h3><p>Complaints come straight to you.</p>',
     '<h3>Ontevreden bellers gaan naar jou</h3><p>Klachten komen direct bij jou terecht.</p>'),
    ('<h3>You see everything</h3><p>Every conversation is saved in your LeadAwaker dashboard, with a recap.</p>',
     '<h3>Jij ziet alles</h3><p>Elk gesprek staat in je LeadAwaker-dashboard, met een samenvatting.</p>'),
    ('<h2>Then she <em class="w">books it</em></h2>',
     '<h2>En dan <em class="w">plant ze het in</em></h2>'),
    ('<span class="eyebrow">Straight into your calendar</span>',
     '<span class="eyebrow">Direct in je agenda</span>'),
    ('<h2>When it can’t wait, <em class="w">she rings you</em></h2>',
     '<h2>Kan het niet wachten? <em class="w">Dan belt ze jou</em></h2>'),
    ('<p>A buyer ready to sign, or a client with an emergency? Sara calls your mobile, briefs you in seconds, and puts them through when you press 1.</p>',
     '<p>Een koper die wil tekenen, of een klant met een noodgeval? Sara belt je mobiel, praat je in een paar seconden bij en verbindt door als je op 1 drukt.</p>'),
    ('alt="A salon receptionist smiling at a customer across the front desk"',
     'alt="Een receptioniste in een salon die een klant aan de balie lachend te woord staat"'),
    ('aria-label="Illustration: a dental practice\'s week. Sara books six appointments into the free slots, from phone calls, website chats and WhatsApp messages."',
     'aria-label="Illustratie: de week van een tandartspraktijk. Sara plant zes afspraken in de vrije tijden, uit telefoontjes, websitechats en WhatsApp-berichten."'),
    ('<b>Brightsmile Dental · this week</b>',
     '<b>Tandartspraktijk Lindenhof · deze week</b>'),
    ('</span> booked by Sara</small>',
     '</span> ingepland door Sara</small>'),
    ('<div class="wk-head"><span></span><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span></div>',
     '<div class="wk-head"><span></span><span>Ma</span><span>Di</span><span>Wo</span><span>Do</span><span>Vr</span></div>'),
    ('<i class="kd tel"></i>Phone</span><span><i class="kd web"></i>Website</span>',
     '<i class="kd tel"></i>Telefoon</span><span><i class="kd web"></i>Website</span>'),
    ('</i>Already booked</span>',
     '</i>Al bezet</span>'),
    ('<span class="os-lbl hot">Ready to buy</span>',
     '<span class="os-lbl hot">Wil kopen</span>'),
    ('<small>Calling your mobile · 10:14</small>',
     '<small>Belt je mobiel · 10:14</small>'),
    ('<b>1</b>Talk to Mark now</span><span class="k2"><b>2</b>Callback in 10 min</span>',
     '<b>1</b>Nu Mark spreken</span><span class="k2"><b>2</b>Over 10 min terugbellen</span>'),
    ('aria-label="Play what the owner hears"',
     'aria-label="Afspelen wat de eigenaar hoort"'),
    ('id="play2-l">What Tom hears</span>',
     'id="play2-l">Wat Tom hoort</span>'),
    ('<span>Works with</span><b>Google Calendar</b><b>Outlook</b><b>and more</b>',
     '<span>Werkt met</span><b>Google Agenda</b><b>Outlook</b><b>en meer</b>'),
    ('<span class="eyebrow">From kick-off to live</span>',
     '<span class="eyebrow">Van kick-off tot live</span>'),
    ('Live in <em class="w">2 weeks</em>, on your own number',
     'Live in <em class="w">2 weken</em>, op je eigen nummer'),
    ('<p>What happens the moment you say yes. Nothing goes live until you have tested her yourself.</p>',
     '<p>Wat er gebeurt zodra je ja zegt. Er gaat niets live voordat je haar zelf hebt getest.</p>'),
    ('<small>Day 1</small><h3>Kick-off call</h3><p>Thirty minutes. How calls come in, what a good call sounds like, your prices, your calendar.</p>',
     '<small>Dag 1</small><h3>Kick-off</h3><p>Een half uur. Hoe gesprekken binnenkomen, hoe een goed gesprek klinkt, je prijzen, je agenda.</p>'),
    ('<small>Day 2 to 5</small><h3>We build Sara</h3><p>Her brief, what she knows from your website, your booking rules, her voice. Written with you, in your words.</p>',
     '<small>Dag 2 t/m 5</small><h3>We bouwen Sara</h3><p>Haar briefing, wat ze van je website weet, je regels voor afspraken, haar stem. Samen met jou geschreven, in jouw woorden.</p>'),
    ('<small>Day 6 to 9</small><h3>Quality tests</h3><p>We put her through test conversations: rushed callers, angry ones, price questions, off-topic chats. Every miss gets fixed.</p>',
     '<small>Dag 6 t/m 9</small><h3>Kwaliteitstests</h3><p>We laten haar testgesprekken voeren: haastige bellers, boze bellers, prijsvragen, gesprekken die alle kanten op gaan. Elke misser wordt opgelost.</p>'),
    ('<small>Day 10 to 12</small><h3>You try to catch her out</h3><p>Ring her, message her, ask the awkward questions. She goes live only when you sign off.</p>',
     '<small>Dag 10 t/m 12</small><h3>Jij probeert haar te betrappen</h3><p>Bel haar, app haar, stel de lastige vragen. Ze gaat pas live als jij akkoord geeft.</p>'),
    ('<small>Day 14</small><h3>Switch on</h3><p>Forward your calls, add the chat to your site, connect WhatsApp and your calendar. Your number stays yours.</p>',
     '<small>Dag 14</small><h3>Aanzetten</h3><p>Schakel je gesprekken door, zet de chat op je site, koppel WhatsApp en je agenda. Je nummer blijft van jou.</p>'),
    ('<small>Week 3 onwards</small><h3>She keeps getting better</h3><p>We read her conversations, A/B test her openings and replies, and send you a short report. Pause her any time.</p>',
     '<small>Vanaf week 3</small><h3>Ze wordt steeds beter</h3><p>We lezen haar gesprekken terug, A/B-testen haar openingen en antwoorden en sturen je een kort rapport. Pauzeren kan altijd.</p>'),
    ('<span class="eyebrow">Who you’ll work with</span>',
     '<span class="eyebrow">Met wie je werkt</span>'),
    ('<h2><span>Systems</span><span>meet</span><em class="w">sales.</em></h2>',
     '<h2><span>Systemen</span><span>én</span><em class="w">sales.</em></h2>'),
    ('<p>One of us builds the systems. The other knows how to sell.</p>',
     '<p>De een bouwt de systemen. De ander weet hoe je verkoopt.</p>'),
    ('<div>Founder<span>Systems &amp; Automation</span></div>',
     '<div>Oprichter<span>Systemen &amp; Automatisering</span></div>'),
    ('<p>12+ years building digital systems, for small businesses and for Warner Bros. and Sega. Today he builds AI that answers, follows up and books.</p>',
     '<p>12+ jaar digitale systemen bouwen voor mkb-bedrijven en namen als Warner Bros. en Sega. Nu bouwt hij AI die opneemt, opvolgt en inplant.</p>'),
    ('<div>Partner<span>Sales &amp; Acquisition</span></div>',
     '<div>Partner<span>Sales &amp; Acquisitie</span></div>'),
    ('<p>Sales strategist who has sold millions in technical projects. He shapes how Sara handles “how much?” and “can you do it sooner?”.</p>',
     '<p>Salesstrateeg die voor miljoenen aan technische projecten verkocht. Hij bepaalt hoe Sara omgaat met “wat kost het?” en “kan het eerder?”.</p>'),
    ('<span class="eyebrow">In their words</span>',
     '<span class="eyebrow">In hun woorden</span>'),
    ('I work with sales software every day, so I don’t impress easily. What stands out with Gabriel is how he builds: he tests everything himself, rings his own receptionist until nothing sounds off, and only then lets a customer hear it.',
     'Ik werk elke dag met salessoftware, dus ik ben niet snel onder de indruk. Wat opvalt aan Gabriel is hoe hij bouwt: hij test alles zelf, belt zijn eigen receptioniste tot er niets meer vreemd klinkt, en pas dan laat hij een klant meeluisteren.'),
    ('Gabriel doesn’t hand you a tool and disappear. He asked how we actually talk to our customers, built around that, and kept adjusting the details. It felt like working with a builder who cares how every sentence sounds.',
     'Gabriel geeft je geen tool om daarna te verdwijnen. Hij vroeg hoe wij echt met onze klanten praten, bouwde daaromheen en bleef de details bijschaven. Het voelde als werken met iemand die erom geeft hoe elke zin klinkt.'),
    ('<small>Co-Founder, FusionCraft</small>',
     '<small>Medeoprichter, FusionCraft</small>'),
    ('<h2>Questions before you book</h2>',
     '<h2>Vragen vooraf</h2>'),
    ('<summary>Does she sound like a robot?</summary><p>No. She talks naturally and lets people interrupt. On the 30-minute call you can ring her and judge for yourself.</p>',
     '<summary>Klinkt ze als een robot?</summary><p>Nee. Ze praat natuurlijk en laat mensen gewoon onderbreken. In ons gesprek kun je haar zelf bellen en oordelen.</p>'),
    ('<summary>Do I have to change my number?</summary><p>No. You forward calls to Sara: when you don’t pick up, after hours, or always.</p>',
     '<summary>Moet ik een ander nummer nemen?</summary><p>Nee. Je schakelt gesprekken door naar Sara: als je niet opneemt, na sluitingstijd of altijd.</p>'),
    ('<summary>Can she book into my calendar?</summary><p>Yes, on the phone, in chat and on WhatsApp. She only offers times you’re free and books straight into Google Calendar, Outlook and other calendar tools. Prefer to ring people first? She books a callback instead.</p>',
     '<summary>Kan ze afspraken in mijn agenda zetten?</summary><p>Ja, aan de telefoon, in de chat en op WhatsApp. Ze biedt alleen tijden aan waarop je vrij bent en zet ze direct in Google Agenda, Outlook en andere agenda’s. Bel je mensen liever eerst zelf? Dan plant ze een terugbelmoment.</p>'),
    ('<summary>Where do I see her conversations?</summary><p>Every call and chat is saved in your LeadAwaker dashboard, with the transcript and a short recap. You also get each recap by email or WhatsApp the moment the conversation ends.</p>',
     '<summary>Waar zie ik haar gesprekken?</summary><p>Elk gesprek en elke chat staat in je LeadAwaker-dashboard, met transcript en een korte samenvatting. Je krijgt elke samenvatting ook per e-mail of WhatsApp zodra het gesprek klaar is.</p>'),
    ('<summary>What if she doesn’t know the answer?</summary><p>She takes a message and sends you the question. She never makes up prices.</p>',
     '<summary>Wat als ze het antwoord niet weet?</summary><p>Dan noteert ze een bericht en stuurt ze de vraag naar jou. Ze verzint nooit prijzen.</p>'),
    ('<summary>What about urgent calls and complaints?</summary><p>You decide what’s urgent, and she can ring your mobile for those. Complaints come straight to you.</p>',
     '<summary>En dringende gesprekken en klachten?</summary><p>Jij bepaalt wat dringend is, en dan kan ze je mobiel bellen. Klachten komen direct bij jou.</p>'),
    ('<summary>Which languages does she speak?</summary><p>English, Dutch and Portuguese.</p>',
     '<summary>Welke talen spreekt ze?</summary><p>Nederlands, Engels en Portugees.</p>'),
    ('<summary>What does it cost?</summary><p>One fixed monthly fee, based on your call volume. You get the price in writing on the first call.</p>',
     '<summary>Wat kost het?</summary><p>Een vast maandbedrag, afhankelijk van je belvolume. Je krijgt de prijs zwart op wit na het eerste gesprek.</p>'),
    ('<summary>What happens to my customers’ data?</summary><p>Conversations are stored on our servers in the Netherlands, and our AI providers work under data processing agreements. You can read or delete any conversation.</p>',
     '<summary>Wat gebeurt er met de gegevens van mijn klanten?</summary><p>Gesprekken staan op onze servers in Nederland, en onze AI-leveranciers werken onder verwerkersovereenkomsten. Je kunt elk gesprek inzien of verwijderen.</p>'),
    ('<h2>Hear your receptionist before you decide</h2>',
     '<h2>Hoor je receptioniste voordat je beslist</h2>'),
    ('<p>20 minutes. We’ll show you Sara answering as the receptionist for your business. Add your website when you book.</p>',
     '<p>20 minuten. We laten Sara horen als receptioniste van jouw bedrijf. Vul bij het inplannen je website in.</p>'),
    ('rel="noopener">Pick a time in the calendar</a>',
     'rel="noopener">Kies een moment in de agenda</a>'),
    ('<span>’s-Hertogenbosch, Netherlands</span>',
     '<span>’s-Hertogenbosch, Nederland</span>'),
    ('<a href="/terms-of-service">Terms &amp; Conditions</a><a href="/privacy-policy">Privacy Policy</a>',
     '<a href="/terms-of-service">Algemene voorwaarden</a><a href="/privacy-policy">Privacybeleid</a>'),
    ('"text": "Hi Tom, it’s Sara. I’ve got Mark Jansen on the line. He test-drove the blue Kia yesterday and wants to buy it today. Press 1 to talk to him now, or press 2 and I’ll tell him you’ll call back in ten minutes."',
     '"text": "Hoi Tom, met Sara. Ik heb Mark Jansen aan de lijn. Hij heeft gisteren een proefrit gemaakt in de blauwe Kia en wil hem vandaag kopen. Druk op 1 om hem nu te spreken, of op 2 en ik zeg dat je hem over tien minuten terugbelt."'),
    ("'Incoming call…'",
     "'Inkomend gesprek…'"),
    ("'Call ended · '",
     "'Gesprek beëindigd · '"),
    ("'Play the call with sound':'Play the call'):hero.mode==='paused'?'Paused · '",
     "'Gesprek afspelen met geluid':'Gesprek afspelen'):hero.mode==='paused'?'Gepauzeerd · '"),
    ("running()?'Pause the call':'Play the call'",
     "running()?'Gesprek pauzeren':'Gesprek afspelen'"),
    ("running()?'Live':hero.mode==='paused'?'Paused':''",
     "running()?'Live':hero.mode==='paused'?'Gepauzeerd':''"),
    ("on?'Back to your phone':'See it in the LeadAwaker platform'",
     "on?'Terug naar je telefoon':'Bekijk het in het LeadAwaker-platform'"),
    ("'Sound could not start here'",
     "'Geluid kon hier niet starten'"),
    ("!R.d.mp3?'What Tom hears'",
     "!R.d.mp3?'Wat Tom hoort'"),
    ("'Hear what Tom hears · '",
     "'Hoor wat Tom hoort · '"),
    ("on?'Hide what the caller hears':'Show what the caller hears'",
     "on?'Verberg wat de beller hoort':'Laat horen wat de beller hoort'"),
    ("var NAMES={phone:'phone',website:'website chat',whatsapp:'WhatsApp'};",
     "var NAMES={phone:'je telefoon',website:'websitechat',whatsapp:'WhatsApp'};"),
    ("+' and '+a[a.length-1]",
     "+' en '+a[a.length-1]"),
    ("'Sara answers your <b>'+list(on)+'</b>':'Sara is switched off. <b>Pick at least one.</b>'",
     "'Sara beantwoordt <b>'+list(on)+'</b>':'Sara staat uit. <b>Kies er minstens één.</b>'"),
    ("[[9,12.25,'On a test drive'],[13.5,17.5,'With a customer'],[18,23,'Showroom closed']]",
     "[[9,12.25,'Op proefrit'],[13.5,17.5,'Bij een klant'],[18,23,'Showroom dicht']]"),
    ("out:'Booked a viewing · Thu 16:00'",
     "out:'Ingepland bezichtiging · Do 16:00'"),
    ("out:'Booked a visit · Fri 11:00'",
     "out:'Ingepland bezoek · Vr 11:00'"),
    ("out:'Booked a valuation · Sat 9:30'",
     "out:'Ingepland taxatie · Za 9:30'"),
    ("out:'Booked a test drive · Mon 15:00'",
     "out:'Ingepland proefrit · Ma 15:00'"),
    ("out:'Answered: open from 9:00'",
     "out:'Beantwoord: open vanaf 9:00'"),
    ("'<b>Booked</b> '+c.out.replace('Booked ','')",
     "'<b>Ingepland</b> '+c.out.replace('Ingepland ','')"),
    ("'Phone<time>'+c.t+'</time></div><p>You answered</p>'",
     "'Telefoon<time>'+c.t+'</time></div><p>Jij nam op</p>'"),
    ("st.textContent=b||'Free'",
     "st.textContent=b||'Vrij'"),
    ("{sum:'Sara today: 5 calls, 4 booked'}",
     "{sum:'Vandaag: 5 gesprekken, 4 ingepland'}"),
    ("o?'Close menu':'Open menu'",
     "o?'Menu sluiten':'Menu openen'"),
    ("DAYS=['Mon','Tue','Wed','Thu','Fri']",
     "DAYS=['Ma','Di','Wo','Do','Vr']"),
    ("var NEW=[{d:1,s:14,e:15,t:'New patient check-up',w:'Anna',ch:'tel'},{d:0,s:15,e:16,t:'Cleaning',w:'Joe',ch:'wa'},{d:2,s:10,e:11,t:'Whitening consult',w:'Sam',ch:'web'},",
     "var NEW=[{d:1,s:14,e:15,t:'Intake nieuwe patiënt',w:'Anouk',ch:'tel'},{d:0,s:15,e:16,t:'Gebitsreiniging',w:'Joost',ch:'wa'},{d:2,s:10,e:11,t:'Consult bleken',w:'Sanne',ch:'web'},"),
    ("{d:3,s:14,e:15,t:'Check-up',w:'Lena',ch:'wa'},{d:4,s:11.5,e:12.5,t:'New patient check-up',w:'Ravi',ch:'web'},{d:3,s:16,e:16.75,t:'Callback',w:'Maria',ch:'tel'}];",
     "{d:3,s:14,e:15,t:'Controle',w:'Lieke',ch:'wa'},{d:4,s:11.5,e:12.5,t:'Intake nieuwe patiënt',w:'Daan',ch:'web'},{d:3,s:16,e:16.75,t:'Terugbellen',w:'Maria',ch:'tel'}];"),
    ("var VIA={tel:'by phone',web:'on the website',wa:'on WhatsApp'};",
     "var VIA={tel:'telefonisch',web:'via de website',wa:'via WhatsApp'};"),
    ("n.w+' booked '+DAYS[n.d]",
     "n.w+' boekte '+DAYS[n.d]"),
    ("var ITEMS=[['Name','Sara'],['Works at','Northgate Motors'],['Voice','Warm and calm'],['Knows','All 48 cars in stock'],['Books','Test drives'],['Answers','Opening hours'],",
     "var ITEMS=[['Naam','Sara'],['Werkt bij','Northgate Motors'],['Stem','Warm en rustig'],['Kent','Alle 48 auto’s op voorraad'],['Plant','Proefritten'],['Beantwoordt','Openingstijden'],"),
    ("['Books','Trade-in valuations'],['Answers','Financing questions'],['Rings Tom','Buyers ready to sign'],['Never','Makes up a price'],['Says','“Tom talks price in person.”'],['Sends','A recap to Tom']];",
     "['Plant','Inruiltaxaties'],['Beantwoordt','Vragen over financiering'],['Belt Tom','Kopers die willen tekenen'],['Nooit','Een prijs verzinnen'],['Zegt','“Over de prijs praat Tom persoonlijk.”'],['Stuurt','Een samenvatting naar Tom']];"),
    ("a.textContent='Open app'",
     "a.textContent='App openen'"),
    (WIDGET_KEY_EN, WIDGET_KEY_NL),
]

if __name__ == "__main__":
    build("nl.html", PAIRS)
