import { useState, useEffect, useRef } from "react";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetDescription,
} from "@/components/ui/sheet";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { apiFetch } from "@/lib/apiUtils";
import { cn } from "@/lib/utils";
import {
  Phone,
  Mail,
  User,
  MessageSquare,
  Calendar,
  Tag,
  Activity,
  Bot,
  StickyNote,
  ExternalLink,
  Loader2,
  Globe,
  ArrowUpCircle,
  BarChart2,
  CheckCircle2,
  X,
  Plus,
  Save,
  Smile,
  Meh,
  Frown,
  Layers,
  PhoneCall,
  UserCheck,
  UserX,
  RefreshCw,
  Pencil,
  Ban,
} from "lucide-react";
import { useLocation } from "wouter";

// ── Types ──────────────────────────────────────────────────────────────────

export interface LeadDetailPanelProps {
  lead: Record<string, any> | null;
  open: boolean;
  onClose: () => void;
}

interface Interaction {
  id: number;
  lead_id?: number;
  Leads_id?: number;
  direction: string;
  /** DB column is uppercase "Content" — API returns this form */
  Content?: string;
  /** fallback lowercase form */
  content?: string;
  created_at?: string;
  type?: string;
  /** DB column is uppercase "Who" — AI agent name or sender identifier */
  Who?: string;
  who?: string;
  /** true when the message was generated by AI */
  ai_generated?: boolean;
  /** true when a human agent manually sent this message */
  is_manual_follow_up?: boolean;
  is_bump?: boolean;
  status?: string;
  sentiment_detected?: string;
}

interface TagData {
  id: number;
  name: string;
  color?: string | null;
  category?: string | null;
  slug?: string | null;
}

interface LeadTagEntry {
  id?: number;
  tagsId?: number;
  Tags_id?: number;
  leadsId?: number;
  Leads_id?: number;
  tagName?: string | null;
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function fmtDate(s: string | null | undefined): string {
  if (!s) return "—";
  try {
    return new Date(s).toLocaleDateString(undefined, {
      day: "2-digit",
      month: "short",
      year: "numeric",
    });
  } catch {
    return s;
  }
}

function fmtDateTime(s: string | null | undefined): string {
  if (!s) return "—";
  try {
    return new Date(s).toLocaleString(undefined, {
      day: "2-digit",
      month: "short",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  } catch {
    return s;
  }
}

const STATUS_COLORS: Record<string, { bg: string; text: string }> = {
  New: { bg: "bg-blue-500/15", text: "text-blue-600 dark:text-blue-400" },
  Contacted: { bg: "bg-indigo-500/15", text: "text-indigo-600 dark:text-indigo-400" },
  Responded: { bg: "bg-violet-500/15", text: "text-violet-600 dark:text-violet-400" },
  "Multiple Responses": { bg: "bg-purple-500/15", text: "text-purple-600 dark:text-purple-400" },
  Qualified: { bg: "bg-emerald-500/15", text: "text-emerald-600 dark:text-emerald-400" },
  Booked: { bg: "bg-amber-400/20", text: "text-brand-yellow font-bold" },
  Lost: { bg: "bg-red-500/15", text: "text-red-600 dark:text-red-400" },
  DND: { bg: "bg-zinc-500/15", text: "text-zinc-600 dark:text-zinc-400" },
};

const PRIORITY_COLORS: Record<string, { bg: string; text: string; ring: string }> = {
  High: { bg: "bg-red-500/15", text: "text-red-600 dark:text-red-400", ring: "ring-1 ring-red-500/30" },
  Medium: { bg: "bg-amber-400/20", text: "text-amber-600 dark:text-amber-400", ring: "ring-1 ring-amber-400/30" },
  Low: { bg: "bg-emerald-500/15", text: "text-emerald-600 dark:text-emerald-400", ring: "ring-1 ring-emerald-500/30" },
};

function StatusBadge({ label }: { label: string }) {
  const colors = STATUS_COLORS[label] ?? { bg: "bg-muted", text: "text-muted-foreground" };
  return (
    <span
      className={cn(
        "inline-flex items-center px-2 py-0.5 rounded-full text-[11px] font-semibold",
        colors.bg,
        colors.text
      )}
    >
      {label}
    </span>
  );
}

function PriorityBadge({ priority }: { priority: string }) {
  const colors = PRIORITY_COLORS[priority] ?? {
    bg: "bg-muted",
    text: "text-muted-foreground",
    ring: "ring-1 ring-border/30",
  };
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[11px] font-semibold",
        colors.bg,
        colors.text,
        colors.ring
      )}
      data-testid="lead-detail-priority-badge"
      data-priority={priority}
    >
      <ArrowUpCircle className="h-3 w-3 shrink-0" />
      {priority}
    </span>
  );
}

function InfoRow({
  icon,
  label,
  value,
  mono = false,
}: {
  icon?: React.ReactNode;
  label: string;
  value: React.ReactNode;
  mono?: boolean;
}) {
  return (
    <div className="flex items-start justify-between gap-3 py-1.5 border-b border-border/30 last:border-0">
      <div className="flex items-center gap-1.5 shrink-0">
        {icon && <span className="text-muted-foreground/60">{icon}</span>}
        <span className="text-[11px] text-muted-foreground">{label}</span>
      </div>
      <span
        className={cn(
          "text-[12px] text-foreground text-right break-words max-w-[58%]",
          mono && "font-mono text-[11px]"
        )}
      >
        {value || "—"}
      </span>
    </div>
  );
}

function SectionTitle({ icon, title }: { icon: React.ReactNode; title: string }) {
  return (
    <div className="flex items-center gap-2 mb-2 mt-4 first:mt-0">
      <span className="text-muted-foreground">{icon}</span>
      <h3 className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
        {title}
      </h3>
    </div>
  );
}

// ── Pipeline Stages ────────────────────────────────────────────────────────

const PIPELINE_STAGES = [
  "New",
  "Contacted",
  "Responded",
  "Multiple Responses",
  "Qualified",
  "Booked",
  "Lost",
  "DND",
] as const;

// ── Sentiment Badge ────────────────────────────────────────────────────────

const SENTIMENT_CONFIG: Record<string, { bg: string; text: string; icon: React.ReactNode }> = {
  positive: {
    bg: "bg-emerald-500/15",
    text: "text-emerald-600 dark:text-emerald-400",
    icon: <Smile className="h-3 w-3" />,
  },
  negative: {
    bg: "bg-red-500/15",
    text: "text-red-600 dark:text-red-400",
    icon: <Frown className="h-3 w-3" />,
  },
  neutral: {
    bg: "bg-zinc-500/15",
    text: "text-zinc-600 dark:text-zinc-400",
    icon: <Meh className="h-3 w-3" />,
  },
};

function SentimentBadge({ sentiment }: { sentiment: string }) {
  const key = sentiment?.toLowerCase() ?? "";
  const config = SENTIMENT_CONFIG[key] ?? {
    bg: "bg-muted",
    text: "text-muted-foreground",
    icon: <Meh className="h-3 w-3" />,
  };
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1.5 px-2 py-0.5 rounded-full text-[11px] font-semibold capitalize",
        config.bg,
        config.text
      )}
      data-testid="ai-sentiment-badge"
      data-sentiment={key}
    >
      {config.icon}
      {sentiment}
    </span>
  );
}

// ── AI Memory Display ──────────────────────────────────────────────────────

function formatAiMemory(raw: string): string {
  if (!raw) return "";
  // Try to parse as JSON and pretty-print
  try {
    const parsed = JSON.parse(raw);
    if (typeof parsed === "object" && parsed !== null) {
      // Format key-value pairs as readable lines
      return Object.entries(parsed)
        .map(([k, v]) => {
          const label = k.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
          const value = typeof v === "object" ? JSON.stringify(v, null, 2) : String(v);
          return `${label}: ${value}`;
        })
        .join("\n");
    }
    return typeof parsed === "string" ? parsed : JSON.stringify(parsed, null, 2);
  } catch {
    return raw; // return as-is if not JSON
  }
}

// ── Inline Edit Field ──────────────────────────────────────────────────────

interface InlineEditFieldProps {
  label: string;
  value: string;
  onSave: (newValue: string) => Promise<void>;
  icon?: React.ReactNode;
  type?: "text" | "email" | "tel";
  testId?: string;
  selectOptions?: string[];
}

function InlineEditField({
  label,
  value,
  onSave,
  icon,
  type = "text",
  testId,
  selectOptions,
}: InlineEditFieldProps) {
  const [editing, setEditing] = useState(false);
  const [localValue, setLocalValue] = useState(value);
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);

  // Sync if parent value changes
  useEffect(() => {
    if (!editing) setLocalValue(value);
  }, [value, editing]);

  const handleStartEdit = () => {
    setLocalValue(value);
    setEditing(true);
    setSaved(false);
    setTimeout(() => inputRef.current?.focus(), 0);
  };

  const handleSave = async () => {
    if (localValue === value) {
      setEditing(false);
      return;
    }
    setSaving(true);
    try {
      await onSave(localValue);
      setSaved(true);
      setTimeout(() => setSaved(false), 2000);
    } finally {
      setSaving(false);
      setEditing(false);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter") { e.preventDefault(); handleSave(); }
    if (e.key === "Escape") { setLocalValue(value); setEditing(false); }
  };

  return (
    <div
      className="flex items-center justify-between gap-3 py-1.5 border-b border-border/30 last:border-0 group"
      data-testid={testId}
    >
      <div className="flex items-center gap-1.5 shrink-0">
        {icon && <span className="text-muted-foreground/60">{icon}</span>}
        <span className="text-[11px] text-muted-foreground">{label}</span>
      </div>

      {editing ? (
        <div className="flex items-center gap-1 flex-1 min-w-0 justify-end">
          {selectOptions ? (
            <select
              value={localValue}
              onChange={(e) => setLocalValue(e.target.value)}
              onBlur={handleSave}
              className="text-[12px] bg-background border border-border rounded px-1.5 py-0.5 max-w-[140px] focus:outline-none focus:ring-1 focus:ring-brand-blue/50"
              data-testid={`${testId}-select`}
              autoFocus
            >
              {selectOptions.map((opt) => (
                <option key={opt} value={opt}>{opt || "—"}</option>
              ))}
            </select>
          ) : (
            <input
              ref={inputRef}
              type={type}
              value={localValue}
              onChange={(e) => setLocalValue(e.target.value)}
              onBlur={handleSave}
              onKeyDown={handleKeyDown}
              className="text-[12px] bg-background border border-border rounded px-1.5 py-0.5 max-w-[160px] focus:outline-none focus:ring-1 focus:ring-brand-blue/50"
              data-testid={`${testId}-input`}
              disabled={saving}
            />
          )}
          {saving && <Loader2 className="h-3 w-3 animate-spin text-muted-foreground shrink-0" />}
        </div>
      ) : (
        <div className="flex items-center gap-1.5 min-w-0">
          {saved && <CheckCircle2 className="h-3 w-3 text-emerald-500 shrink-0" />}
          <span className="text-[12px] text-foreground text-right break-words max-w-[140px] truncate">
            {value || "—"}
          </span>
          <button
            type="button"
            onClick={handleStartEdit}
            className="opacity-0 group-hover:opacity-100 transition-opacity ml-0.5 text-muted-foreground/60 hover:text-brand-blue"
            aria-label={`Edit ${label}`}
            data-testid={`${testId}-edit-btn`}
          >
            <Pencil className="h-3 w-3" />
          </button>
        </div>
      )}
    </div>
  );
}

// ── Score Gauge ────────────────────────────────────────────────────────────

function scoreColor(value: number): { bar: string; text: string } {
  if (value < 30) return { bar: "bg-red-500", text: "text-red-600 dark:text-red-400" };
  if (value <= 70) return { bar: "bg-amber-400", text: "text-amber-600 dark:text-amber-400" };
  return { bar: "bg-emerald-500", text: "text-emerald-600 dark:text-emerald-400" };
}

function ScoreGauge({
  label,
  value,
  testId,
}: {
  label: string;
  value: number | null | undefined;
  testId: string;
}) {
  const numVal = typeof value === "number" ? Math.max(0, Math.min(100, value)) : null;
  const colors = numVal !== null ? scoreColor(numVal) : { bar: "bg-muted", text: "text-muted-foreground" };

  return (
    <div className="flex flex-col gap-1" data-testid={testId}>
      <div className="flex items-center justify-between">
        <span className="text-[11px] text-muted-foreground">{label}</span>
        <span className={cn("text-[12px] font-bold tabular-nums", colors.text)} data-testid={`${testId}-value`}>
          {numVal !== null ? numVal : "—"}
          {numVal !== null && <span className="text-[10px] font-normal text-muted-foreground ml-0.5">/100</span>}
        </span>
      </div>
      {/* Track */}
      <div className="h-2 w-full rounded-full bg-muted overflow-hidden" data-testid={`${testId}-track`}>
        <div
          className={cn("h-full rounded-full transition-all duration-500", colors.bar)}
          style={{ width: numVal !== null ? `${numVal}%` : "0%" }}
          data-testid={`${testId}-bar`}
        />
      </div>
    </div>
  );
}

// ── Main Component ────────────────────────────────────────────────────────

export function LeadDetailPanel({ lead, open, onClose }: LeadDetailPanelProps) {
  const [, setLocation] = useLocation();
  const [interactions, setInteractions] = useState<Interaction[]>([]);
  const [loadingInteractions, setLoadingInteractions] = useState(false);
  const [localStatus, setLocalStatus] = useState<string>("");
  const [savingStatus, setSavingStatus] = useState(false);
  const [stageSaved, setStageSaved] = useState(false);

  // ── Tags state ──
  const [leadTags, setLeadTags] = useState<TagData[]>([]);
  const [availableTags, setAvailableTags] = useState<TagData[]>([]);
  const [loadingTags, setLoadingTags] = useState(false);
  const [addingTag, setAddingTag] = useState(false);
  const [removingTagId, setRemovingTagId] = useState<number | null>(null);
  const [showTagDropdown, setShowTagDropdown] = useState(false);

  // ── Notes editing state ──
  const [localNotes, setLocalNotes] = useState<string>("");
  const [notesDirty, setNotesDirty] = useState(false);
  const [savingNotes, setSavingNotes] = useState(false);
  const [notesSaved, setNotesSaved] = useState(false);
  const notesOriginalRef = useRef<string>("");

  // ── Manual takeover toggle state ──
  const [localManualTakeover, setLocalManualTakeover] = useState<boolean>(false);
  const [savingManualTakeover, setSavingManualTakeover] = useState(false);

  // ── DNC / Opted-out state ──
  const [localOptedOut, setLocalOptedOut] = useState<boolean>(false);
  const [localDncReason, setLocalDncReason] = useState<string>("");
  const [savingDnc, setSavingDnc] = useState(false);
  const [dncSaved, setDncSaved] = useState(false);
  const [showDncReason, setShowDncReason] = useState(false);

  const leadId = lead?.Id || lead?.id;

  // Sync localStatus when lead changes
  useEffect(() => {
    const status = lead?.conversion_status || lead?.Conversion_Status || "";
    setLocalStatus(status);
    setStageSaved(false);
  }, [lead?.Id, lead?.id, lead?.Conversion_Status, lead?.conversion_status]);

  // Sync notes when lead changes
  useEffect(() => {
    const notes = lead?.notes || "";
    notesOriginalRef.current = notes;
    setLocalNotes(notes);
    setNotesDirty(false);
    setNotesSaved(false);
  }, [lead?.Id, lead?.id, lead?.notes]);

  // Sync manual_takeover when lead changes
  useEffect(() => {
    setLocalManualTakeover(Boolean(lead?.manual_takeover));
  }, [lead?.Id, lead?.id, lead?.manual_takeover]);

  // Sync DNC / opted-out state when lead changes
  useEffect(() => {
    const optedOut = Boolean(lead?.opted_out);
    setLocalOptedOut(optedOut);
    setLocalDncReason(lead?.dnc_reason || "");
    setShowDncReason(optedOut);
    setDncSaved(false);
  }, [lead?.Id, lead?.id, lead?.opted_out, lead?.dnc_reason]);

  // Fetch interactions when panel opens with a lead
  useEffect(() => {
    if (!open || !leadId) {
      setInteractions([]);
      return;
    }

    let cancelled = false;
    setLoadingInteractions(true);

    // Fetch all interactions — no limit query param (API returns all when no ?page= given)
    apiFetch(`/api/interactions?leadId=${leadId}`)
      .then((r) => r.ok ? r.json() : null)
      .then((data) => {
        if (cancelled) return;
        const list: Interaction[] = Array.isArray(data) ? data : data?.list || data?.data || [];
        // Sort chronologically ascending (oldest first) — API returns DESC by default
        list.sort((a, b) => {
          const ta = a.created_at ? new Date(a.created_at).getTime() : 0;
          const tb = b.created_at ? new Date(b.created_at).getTime() : 0;
          return ta - tb;
        });
        setInteractions(list);
      })
      .catch(() => {
        if (!cancelled) setInteractions([]);
      })
      .finally(() => {
        if (!cancelled) setLoadingInteractions(false);
      });

    return () => { cancelled = true; };
  }, [open, leadId]);

  // ── Fetch lead tags when panel opens ──
  useEffect(() => {
    if (!open || !leadId) {
      setLeadTags([]);
      setShowTagDropdown(false);
      return;
    }

    let cancelled = false;
    setLoadingTags(true);

    // Fetch lead's current tags (returns Leads_Tags rows with tagName denormalized)
    apiFetch(`/api/leads/${leadId}/tags`)
      .then((r) => r.ok ? r.json() : [])
      .then((data: LeadTagEntry[]) => {
        if (cancelled) return;
        const arr = Array.isArray(data) ? data : [];
        // Convert LeadTagEntry rows to TagData for display
        // The Leads_Tags table has a tagName denormalized field
        const tagList: TagData[] = arr
          .filter((e) => e.tagsId || e.Tags_id)
          .map((e) => ({
            id: e.tagsId ?? e.Tags_id ?? 0,
            name: e.tagName || `Tag #${e.tagsId ?? e.Tags_id}`,
            color: null,
            category: null,
          }));
        setLeadTags(tagList);
      })
      .catch(() => { if (!cancelled) setLeadTags([]); })
      .finally(() => { if (!cancelled) setLoadingTags(false); });

    return () => { cancelled = true; };
  }, [open, leadId]);

  // ── Fetch available tags once ──
  useEffect(() => {
    if (!open) return;
    apiFetch("/api/tags")
      .then((r) => r.ok ? r.json() : Promise.resolve([]))
      .then((data: any) => {
        const arr: any[] = Array.isArray(data) ? data : data?.list || data?.data || [];
        setAvailableTags(arr.map((t: any) => ({
          id: t.Id ?? t.id,
          name: t.Name ?? t.name ?? "Tag",
          color: t.Color ?? t.color ?? null,
          category: t.Category ?? t.category ?? null,
          slug: t.Slug ?? t.slug ?? null,
        })));
      })
      .catch(() => {});
  }, [open]);

  const handleAddTag = async (tag: TagData) => {
    if (!leadId) return;
    // Already assigned?
    if (leadTags.some((t) => t.id === tag.id)) {
      setShowTagDropdown(false);
      return;
    }
    setAddingTag(true);
    try {
      const res = await apiFetch(`/api/leads/${leadId}/tags`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ tagId: tag.id }),
      });
      if (res.ok) {
        setLeadTags((prev) => [...prev, tag]);
      }
    } catch {
      // silently ignore
    } finally {
      setAddingTag(false);
      setShowTagDropdown(false);
    }
  };

  const handleRemoveTag = async (tagId: number) => {
    if (!leadId) return;
    setRemovingTagId(tagId);
    try {
      const res = await apiFetch(`/api/leads/${leadId}/tags/${tagId}`, {
        method: "DELETE",
      });
      if (res.ok) {
        setLeadTags((prev) => prev.filter((t) => t.id !== tagId));
      }
    } catch {
      // silently ignore
    } finally {
      setRemovingTagId(null);
    }
  };

  // Derive available tags that aren't yet assigned
  const unassignedTags = availableTags.filter(
    (t) => !leadTags.some((lt) => lt.id === t.id)
  );

  const handleStageChange = async (newStage: string) => {
    if (!leadId || newStage === localStatus) return;

    const prevStatus = localStatus;
    setLocalStatus(newStage); // optimistic update
    setSavingStatus(true);
    setStageSaved(false);

    try {
      const res = await apiFetch(`/api/leads/${leadId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ Conversion_Status: newStage }),
      });
      if (!res.ok) {
        setLocalStatus(prevStatus); // revert on error
      } else {
        setStageSaved(true);
        // Clear the "saved" checkmark after 2 seconds
        setTimeout(() => setStageSaved(false), 2000);
      }
    } catch {
      setLocalStatus(prevStatus); // revert on error
    } finally {
      setSavingStatus(false);
    }
  };

  const handleNotesSave = async () => {
    if (!leadId || !notesDirty || savingNotes) return;
    setSavingNotes(true);
    setNotesSaved(false);
    try {
      const res = await apiFetch(`/api/leads/${leadId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ notes: localNotes }),
      });
      if (res.ok) {
        notesOriginalRef.current = localNotes;
        setNotesDirty(false);
        setNotesSaved(true);
        setTimeout(() => setNotesSaved(false), 2000);
      }
    } catch {
      // silently fail — user can retry
    } finally {
      setSavingNotes(false);
    }
  };

  const handleManualTakeoverChange = async (checked: boolean) => {
    if (!leadId || savingManualTakeover) return;
    const prev = localManualTakeover;
    setLocalManualTakeover(checked); // optimistic update
    setSavingManualTakeover(true);
    try {
      const res = await apiFetch(`/api/leads/${leadId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ manual_takeover: checked }),
      });
      if (!res.ok) {
        setLocalManualTakeover(prev); // revert on error
      }
    } catch {
      setLocalManualTakeover(prev);
    } finally {
      setSavingManualTakeover(false);
    }
  };

  // Generic inline field save handler (patches lead by field name)
  const handleInlineFieldSave = async (fieldName: string, newValue: string) => {
    if (!leadId) return;
    await apiFetch(`/api/leads/${leadId}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ [fieldName]: newValue }),
    });
  };

  const handleDncChange = async (checked: boolean) => {
    if (!leadId || savingDnc) return;
    const prev = localOptedOut;
    setLocalOptedOut(checked);
    setShowDncReason(checked);
    setSavingDnc(true);
    setDncSaved(false);
    try {
      const payload: Record<string, any> = { opted_out: checked };
      if (!checked) payload.dnc_reason = "";
      const res = await apiFetch(`/api/leads/${leadId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });
      if (!res.ok) {
        setLocalOptedOut(prev);
        setShowDncReason(prev);
      } else {
        if (!checked) setLocalDncReason("");
        setDncSaved(true);
        setTimeout(() => setDncSaved(false), 2000);
      }
    } catch {
      setLocalOptedOut(prev);
      setShowDncReason(prev);
    } finally {
      setSavingDnc(false);
    }
  };

  const handleDncReasonSave = async () => {
    if (!leadId || savingDnc) return;
    setSavingDnc(true);
    try {
      await apiFetch(`/api/leads/${leadId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ dnc_reason: localDncReason }),
      });
      setDncSaved(true);
      setTimeout(() => setDncSaved(false), 2000);
    } catch {
      // silently ignore
    } finally {
      setSavingDnc(false);
    }
  };

  if (!lead) return null;

  const fullName = lead.full_name || [lead.first_name, lead.last_name].filter(Boolean).join(" ") || "Unknown";
  const convStatus = localStatus || lead.conversion_status || lead.Conversion_Status || "";
  const autoStatus = lead.automation_status || lead.Automation_Status || "";
  const email = lead.email || lead.Email || "";
  const source = lead.Source || lead.source || lead.inquiries_source || "";
  const priority = lead.priority || lead.Priority || "";
  const isAgency = window.location.pathname.startsWith("/agency");

  const handleViewFull = () => {
    onClose();
    const path = isAgency ? `/agency/contacts/${leadId}` : `/subaccount/contacts/${leadId}`;
    setLocation(path);
  };

  return (
    <Sheet open={open} onOpenChange={(v) => { if (!v) onClose(); }}>
      <SheetContent
        side="right"
        className="w-[420px] sm:max-w-[420px] p-0 flex flex-col overflow-hidden bg-background text-foreground dark:bg-card dark:border-border"
        data-testid="lead-detail-panel"
      >
        {/* Header */}
        <SheetHeader
          className="px-5 pt-5 pb-4 border-b border-border shrink-0"
          data-testid="lead-info-header"
        >
          {/* Row 1: label + status badge */}
          <div className="flex items-center justify-between gap-2 mb-0.5">
            <div className="text-[10px] font-semibold uppercase tracking-widest text-muted-foreground">
              Lead Detail
            </div>
            <div className="flex items-center gap-1.5 flex-wrap justify-end">
              {convStatus && <StatusBadge label={convStatus} />}
              {priority && <PriorityBadge priority={priority} />}
            </div>
          </div>

          {/* Row 2: name (most prominent) */}
          <SheetTitle
            className="text-[18px] font-bold leading-tight truncate"
            data-testid="lead-detail-panel-name"
          >
            {fullName}
          </SheetTitle>

          {/* Row 3: contact meta — phone, email, source */}
          <div className="mt-2 flex flex-col gap-1" data-testid="lead-header-meta">
            {lead.phone && (
              <div
                className="flex items-center gap-1.5 text-[12px] text-muted-foreground"
                data-testid="lead-detail-panel-phone"
              >
                <Phone className="h-3 w-3 shrink-0 text-muted-foreground/60" />
                <span className="font-mono">{lead.phone}</span>
              </div>
            )}
            {email && (
              <div
                className="flex items-center gap-1.5 text-[12px] text-muted-foreground"
                data-testid="lead-detail-panel-email"
              >
                <Mail className="h-3 w-3 shrink-0 text-muted-foreground/60" />
                <span className="truncate">{email}</span>
              </div>
            )}
            {source && (
              <div
                className="flex items-center gap-1.5 text-[12px] text-muted-foreground"
                data-testid="lead-detail-panel-source"
              >
                <Globe className="h-3 w-3 shrink-0 text-muted-foreground/60" />
                <span>Source: <span className="text-foreground/80">{source}</span></span>
              </div>
            )}
            {autoStatus && (
              <SheetDescription className="text-[11px] mt-0.5">
                {autoStatus}
              </SheetDescription>
            )}
          </div>

          {/* Row 4: View full page */}
          <button
            onClick={handleViewFull}
            className="mt-2 inline-flex items-center gap-1.5 text-[11px] text-brand-blue hover:text-brand-blue/80 font-medium transition-colors"
            data-testid="lead-detail-panel-view-full"
          >
            <ExternalLink className="h-3 w-3" />
            Open full contact page
          </button>
        </SheetHeader>

        {/* Scrollable body */}
        <div className="flex-1 overflow-y-auto px-5 py-4" data-testid="lead-detail-panel-body">

          {/* Contact Info — with inline editing */}
          <SectionTitle icon={<User className="h-3.5 w-3.5" />} title="Contact" />
          <div
            className="rounded-xl border border-border/40 bg-muted/20 px-3 py-1.5"
            data-testid="contact-info-section"
          >
            <InlineEditField
              label="Name"
              value={fullName}
              icon={<User className="h-3 w-3" />}
              onSave={(v) => handleInlineFieldSave("full_name", v)}
              testId="inline-edit-name"
            />
            <InlineEditField
              label="Phone"
              value={lead.phone || ""}
              icon={<Phone className="h-3 w-3" />}
              type="tel"
              onSave={(v) => handleInlineFieldSave("phone", v)}
              testId="inline-edit-phone"
            />
            <InlineEditField
              label="Email"
              value={lead.email || ""}
              icon={<Mail className="h-3 w-3" />}
              type="email"
              onSave={(v) => handleInlineFieldSave("email", v)}
              testId="inline-edit-email"
            />
            <InlineEditField
              label="Priority"
              value={lead.priority || ""}
              icon={<Activity className="h-3 w-3" />}
              onSave={(v) => handleInlineFieldSave("priority", v)}
              selectOptions={["", "High", "Medium", "Low"]}
              testId="inline-edit-priority"
            />
            <InfoRow
              label="Language"
              value={lead.language}
            />
          </div>

          {/* Lead Scores */}
          {(lead.lead_score != null || lead.engagement_score != null || lead.activity_score != null) && (
            <>
              <SectionTitle icon={<BarChart2 className="h-3.5 w-3.5" />} title="Scores" />
              <div
                className="rounded-xl border border-border/40 bg-muted/20 px-3 py-3 flex flex-col gap-3"
                data-testid="lead-score-gauges"
              >
                <ScoreGauge
                  label="Lead Score"
                  value={lead.lead_score}
                  testId="lead-score-gauge-overall"
                />
                <ScoreGauge
                  label="Engagement"
                  value={lead.engagement_score}
                  testId="lead-score-gauge-engagement"
                />
                <ScoreGauge
                  label="Activity"
                  value={lead.activity_score}
                  testId="lead-score-gauge-activity"
                />
              </div>
            </>
          )}

          {/* Status */}
          <SectionTitle icon={<Activity className="h-3.5 w-3.5" />} title="Status" />
          <div className="rounded-xl border border-border/40 bg-muted/20 px-3 py-1.5">
            {/* Pipeline Stage — interactive dropdown */}
            <div
              className="flex items-start justify-between gap-3 py-1.5 border-b border-border/30"
              data-testid="pipeline-stage-row"
            >
              <div className="flex items-center gap-1.5 shrink-0">
                <span className="text-[11px] text-muted-foreground">Pipeline Stage</span>
              </div>
              <div className="flex items-center gap-1.5 flex-wrap justify-end">
                {/* Current stage badge (visual indicator) */}
                {convStatus && <StatusBadge label={convStatus} />}

                {/* Change dropdown */}
                <Select
                  value={convStatus}
                  onValueChange={handleStageChange}
                  disabled={savingStatus}
                >
                  <SelectTrigger
                    className="h-6 w-auto min-w-[70px] text-[11px] px-2 py-0 border-dashed border-border/60 bg-transparent hover:bg-muted/40 transition-colors"
                    data-testid="pipeline-stage-trigger"
                    aria-label="Change pipeline stage"
                  >
                    <SelectValue placeholder="Change…" />
                  </SelectTrigger>
                  <SelectContent data-testid="pipeline-stage-dropdown">
                    {PIPELINE_STAGES.map((stage) => {
                      const colors = STATUS_COLORS[stage] ?? { bg: "bg-muted", text: "text-muted-foreground" };
                      return (
                        <SelectItem
                          key={stage}
                          value={stage}
                          className="text-[12px]"
                          data-testid={`pipeline-stage-option-${stage.replace(/\s+/g, "-").toLowerCase()}`}
                        >
                          <span
                            className={cn(
                              "inline-flex items-center gap-1.5 px-1.5 py-0.5 rounded-full text-[11px] font-semibold",
                              colors.bg,
                              colors.text
                            )}
                          >
                            {stage}
                          </span>
                        </SelectItem>
                      );
                    })}
                  </SelectContent>
                </Select>

                {/* Saving/saved indicator */}
                {savingStatus && (
                  <Loader2
                    className="h-3 w-3 animate-spin text-muted-foreground"
                    data-testid="pipeline-stage-saving"
                  />
                )}
                {stageSaved && !savingStatus && (
                  <CheckCircle2
                    className="h-3.5 w-3.5 text-emerald-500"
                    data-testid="pipeline-stage-saved"
                  />
                )}
              </div>
            </div>

            <InfoRow label="Automation" value={autoStatus} />

            {/* Manual Takeover — toggle switch */}
            <div
              className="flex items-center justify-between gap-3 py-1.5 border-t border-border/30"
              data-testid="manual-takeover-row"
            >
              <div className="flex items-center gap-1.5 shrink-0">
                <span className="text-muted-foreground/60">
                  {localManualTakeover ? <UserX className="h-3 w-3" /> : <UserCheck className="h-3 w-3" />}
                </span>
                <span className="text-[11px] text-muted-foreground">Manual Takeover</span>
                {localManualTakeover && (
                  <span className="text-[10px] font-semibold text-amber-600 dark:text-amber-400 bg-amber-400/15 px-1.5 py-px rounded-full">
                    AI paused
                  </span>
                )}
              </div>
              <div className="flex items-center gap-1.5">
                {savingManualTakeover && <Loader2 className="h-3 w-3 animate-spin text-muted-foreground" />}
                <Switch
                  checked={localManualTakeover}
                  onCheckedChange={handleManualTakeoverChange}
                  disabled={savingManualTakeover}
                  data-testid="manual-takeover-toggle"
                  aria-label="Toggle manual takeover"
                />
              </div>
            </div>
          </div>

          {/* DNC / Opted-out Section */}
          <SectionTitle icon={<Ban className="h-3.5 w-3.5" />} title="Do Not Contact" />
          <div
            className="rounded-xl border border-border/40 bg-muted/20 px-3 py-2"
            data-testid="dnc-section"
          >
            {/* Opted-out toggle */}
            <div
              className="flex items-center justify-between gap-3 py-1.5"
              data-testid="dnc-toggle-row"
            >
              <div className="flex items-center gap-1.5">
                <Ban className="h-3 w-3 text-muted-foreground/60" />
                <span className="text-[11px] text-muted-foreground">Opted Out / DNC</span>
                {localOptedOut && (
                  <span className="text-[10px] font-semibold text-red-600 dark:text-red-400 bg-red-500/15 px-1.5 py-px rounded-full">
                    DNC active
                  </span>
                )}
              </div>
              <div className="flex items-center gap-1.5">
                {savingDnc && <Loader2 className="h-3 w-3 animate-spin text-muted-foreground" />}
                {dncSaved && !savingDnc && <CheckCircle2 className="h-3 w-3 text-emerald-500" />}
                <Switch
                  checked={localOptedOut}
                  onCheckedChange={handleDncChange}
                  disabled={savingDnc}
                  data-testid="dnc-toggle"
                  aria-label="Toggle DNC / opted-out status"
                />
              </div>
            </div>

            {/* DNC reason input — shows when opted out */}
            {showDncReason && (
              <div className="mt-1.5 pt-1.5 border-t border-border/30" data-testid="dnc-reason-container">
                <label className="text-[11px] text-muted-foreground mb-1 block">Reason (optional)</label>
                <div className="flex gap-1.5">
                  <input
                    type="text"
                    value={localDncReason}
                    onChange={(e) => setLocalDncReason(e.target.value)}
                    onBlur={handleDncReasonSave}
                    onKeyDown={(e) => { if (e.key === "Enter") handleDncReasonSave(); }}
                    placeholder="Enter DNC reason…"
                    className="flex-1 text-[12px] bg-background border border-border/60 rounded px-2 py-1 focus:outline-none focus:ring-1 focus:ring-brand-blue/50"
                    data-testid="dnc-reason-input"
                    disabled={savingDnc}
                  />
                </div>
                {localDncReason && (
                  <p className="mt-1 text-[11px] text-muted-foreground" data-testid="dnc-reason-display">
                    Reason: <span className="text-foreground/80">{localDncReason}</span>
                  </p>
                )}
              </div>
            )}
          </div>

          {/* Bump Stage Indicator */}
          {(lead.current_bump_stage != null || lead.bump_1_sent_at || lead.bump_2_sent_at || lead.bump_3_sent_at) && (
            <>
              <SectionTitle icon={<Layers className="h-3.5 w-3.5" />} title="Bump Progress" />
              <div
                className="rounded-xl border border-border/40 bg-muted/20 px-3 py-3"
                data-testid="bump-stage-section"
              >
                {/* Stage progress bar */}
                <div className="flex items-center gap-1 mb-3">
                  {[1, 2, 3].map((stage) => {
                    const currentStage = Number(lead.current_bump_stage ?? 0);
                    const done = currentStage >= stage;
                    return (
                      <div
                        key={stage}
                        className={cn(
                          "flex-1 h-2 rounded-full transition-all duration-300",
                          done ? "bg-brand-blue" : "bg-muted"
                        )}
                        data-testid={`bump-stage-step-${stage}`}
                        data-done={done ? "true" : "false"}
                      />
                    );
                  })}
                </div>

                {/* Current stage label */}
                <div className="flex items-center justify-between mb-2">
                  <span className="text-[11px] text-muted-foreground">Current Stage</span>
                  <span
                    className="text-[12px] font-semibold text-foreground tabular-nums"
                    data-testid="bump-current-stage"
                  >
                    {lead.current_bump_stage ?? 0} / 3
                  </span>
                </div>

                {/* Bump timestamps */}
                {lead.bump_1_sent_at && (
                  <div className="flex items-center justify-between py-0.5">
                    <span className="text-[11px] text-muted-foreground">Bump 1</span>
                    <span className="text-[11px] text-foreground/80 tabular-nums" data-testid="bump-1-sent-at">
                      {fmtDateTime(lead.bump_1_sent_at)}
                    </span>
                  </div>
                )}
                {lead.bump_2_sent_at && (
                  <div className="flex items-center justify-between py-0.5">
                    <span className="text-[11px] text-muted-foreground">Bump 2</span>
                    <span className="text-[11px] text-foreground/80 tabular-nums" data-testid="bump-2-sent-at">
                      {fmtDateTime(lead.bump_2_sent_at)}
                    </span>
                  </div>
                )}
                {lead.bump_3_sent_at && (
                  <div className="flex items-center justify-between py-0.5">
                    <span className="text-[11px] text-muted-foreground">Bump 3</span>
                    <span className="text-[11px] text-foreground/80 tabular-nums" data-testid="bump-3-sent-at">
                      {fmtDateTime(lead.bump_3_sent_at)}
                    </span>
                  </div>
                )}
              </div>
            </>
          )}

          {/* Activity */}
          <SectionTitle icon={<MessageSquare className="h-3.5 w-3.5" />} title="Activity" />
          <div className="rounded-xl border border-border/40 bg-muted/20 px-3 py-1.5">
            <InfoRow label="Last Interaction" value={fmtDateTime(lead.last_interaction_at)} />
            <InfoRow label="Last Sent" value={fmtDateTime(lead.last_message_sent_at)} />
            <InfoRow label="Last Received" value={fmtDateTime(lead.last_message_received_at)} />
            <InfoRow label="Sent Count" value={lead.message_count_sent} />
            <InfoRow label="Received Count" value={lead.message_count_received} />
            <InfoRow label="First Contacted" value={fmtDate(lead.first_message_sent_at)} />
            <InfoRow label="Next Action" value={fmtDateTime(lead.next_action_at)} />
          </div>

          {/* Booking */}
          {(lead.booked_call_date || lead.booking_confirmed_at) && (
            <>
              <SectionTitle icon={<PhoneCall className="h-3.5 w-3.5" />} title="Booking" />
              <div
                className="rounded-xl border border-border/40 bg-muted/20 px-3 py-1.5"
                data-testid="booked-call-section"
              >
                <InfoRow label="Call Date" value={fmtDate(lead.booked_call_date)} />
                <InfoRow label="Confirmed At" value={fmtDateTime(lead.booking_confirmed_at)} />
                {/* No-show indicator */}
                <div className="flex items-start justify-between gap-3 py-1.5 border-b border-border/30 last:border-0">
                  <span className="text-[11px] text-muted-foreground shrink-0">No Show</span>
                  {lead.no_show ? (
                    <span
                      className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[11px] font-semibold bg-red-500/15 text-red-600 dark:text-red-400"
                      data-testid="no-show-badge"
                    >
                      <X className="h-3 w-3" />
                      No Show
                    </span>
                  ) : (
                    <span className="text-[12px] text-muted-foreground">—</span>
                  )}
                </div>
                {/* Reschedule count */}
                {lead.re_scheduled_count != null && lead.re_scheduled_count > 0 && (
                  <div className="flex items-center justify-between gap-3 py-1.5 border-b border-border/30 last:border-0">
                    <div className="flex items-center gap-1.5 shrink-0">
                      <RefreshCw className="h-3 w-3 text-muted-foreground/60" />
                      <span className="text-[11px] text-muted-foreground">Rescheduled</span>
                    </div>
                    <span
                      className="text-[12px] font-semibold text-amber-600 dark:text-amber-400 tabular-nums"
                      data-testid="reschedule-count"
                    >
                      {lead.re_scheduled_count}×
                    </span>
                  </div>
                )}
              </div>
            </>
          )}

          {/* AI Insights */}
          {(lead.ai_sentiment || lead.ai_memory) && (
            <>
              <SectionTitle icon={<Bot className="h-3.5 w-3.5" />} title="AI Insights" />
              <div
                className="rounded-xl border border-border/40 bg-muted/20 px-3 py-1.5"
                data-testid="ai-insights-section"
              >
                {/* Sentiment badge — color coded */}
                {lead.ai_sentiment && (
                  <div className="flex items-start justify-between gap-3 py-1.5 border-b border-border/30 last:border-0">
                    <span className="text-[11px] text-muted-foreground shrink-0">Sentiment</span>
                    <SentimentBadge sentiment={lead.ai_sentiment} />
                  </div>
                )}
                {/* AI memory — formatted readably */}
                {lead.ai_memory && (
                  <div className="py-1.5" data-testid="ai-memory-display">
                    <div className="text-[11px] text-muted-foreground mb-1.5">AI Memory</div>
                    <pre className="text-[11px] text-foreground/80 leading-relaxed whitespace-pre-wrap font-sans break-words">
                      {formatAiMemory(lead.ai_memory)}
                    </pre>
                  </div>
                )}
              </div>
            </>
          )}

          {/* Notes — editable */}
          <div data-testid="lead-notes-section">
            <div className="flex items-center justify-between mb-2 mt-4">
              <div className="flex items-center gap-2">
                <span className="text-muted-foreground"><StickyNote className="h-3.5 w-3.5" /></span>
                <h3 className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">Notes</h3>
              </div>
              <div className="flex items-center gap-1.5">
                {savingNotes && (
                  <Loader2
                    className="h-3 w-3 animate-spin text-muted-foreground"
                    data-testid="notes-saving-indicator"
                  />
                )}
                {notesSaved && !savingNotes && (
                  <span className="flex items-center gap-1 text-[10px] text-emerald-600 dark:text-emerald-400" data-testid="notes-saved-indicator">
                    <CheckCircle2 className="h-3 w-3" />
                    Saved
                  </span>
                )}
                {notesDirty && !savingNotes && (
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={handleNotesSave}
                    className="h-6 px-2 text-[11px] gap-1"
                    data-testid="notes-save-button"
                    aria-label="Save notes"
                  >
                    <Save className="h-3 w-3" />
                    Save
                  </Button>
                )}
              </div>
            </div>
            <div className="rounded-xl border border-border/40 bg-muted/20 p-2">
              <Textarea
                value={localNotes}
                onChange={(e) => {
                  setLocalNotes(e.target.value);
                  setNotesDirty(e.target.value !== notesOriginalRef.current);
                  setNotesSaved(false);
                }}
                onBlur={handleNotesSave}
                placeholder="Add notes about this lead…"
                className="min-h-[80px] resize-none text-[12px] bg-transparent border-0 shadow-none focus-visible:ring-0 p-1 leading-relaxed"
                data-testid="lead-notes-textarea"
                disabled={savingNotes}
              />
            </div>
          </div>

          {/* Tags */}
          <SectionTitle icon={<Tag className="h-3.5 w-3.5" />} title="Tags" />
          <div
            className="rounded-xl border border-border/40 bg-muted/20 px-3 py-3"
            data-testid="lead-detail-tags-section"
          >
            {loadingTags ? (
              <div className="flex items-center gap-2 text-[12px] text-muted-foreground">
                <Loader2 className="h-3.5 w-3.5 animate-spin" />
                Loading tags…
              </div>
            ) : (
              <div className="flex flex-wrap gap-1.5" data-testid="lead-tags-chips">
                {/* Existing tag chips */}
                {leadTags.map((tag) => (
                  <span
                    key={tag.id}
                    className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[11px] font-semibold bg-violet-500/15 text-violet-700 dark:text-violet-300 ring-1 ring-violet-500/20"
                    data-testid={`lead-tag-chip-${tag.id}`}
                    data-tag-id={tag.id}
                    data-tag-name={tag.name}
                  >
                    <Tag className="h-2.5 w-2.5 shrink-0" />
                    {tag.name}
                    <button
                      type="button"
                      onClick={() => handleRemoveTag(tag.id)}
                      disabled={removingTagId === tag.id}
                      className="ml-0.5 rounded-full hover:bg-violet-500/20 transition-colors disabled:opacity-50"
                      aria-label={`Remove tag ${tag.name}`}
                      data-testid={`lead-tag-remove-${tag.id}`}
                    >
                      {removingTagId === tag.id
                        ? <Loader2 className="h-2.5 w-2.5 animate-spin" />
                        : <X className="h-2.5 w-2.5" />
                      }
                    </button>
                  </span>
                ))}

                {/* Add tag button + dropdown */}
                <div className="relative">
                  <button
                    type="button"
                    onClick={() => setShowTagDropdown((v) => !v)}
                    disabled={addingTag}
                    className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[11px] font-medium border border-dashed border-border/60 text-muted-foreground hover:text-foreground hover:border-border transition-colors disabled:opacity-50"
                    data-testid="lead-tag-add-button"
                    aria-label="Add tag"
                  >
                    {addingTag
                      ? <Loader2 className="h-2.5 w-2.5 animate-spin" />
                      : <Plus className="h-2.5 w-2.5" />
                    }
                    Add tag
                  </button>

                  {/* Tag selection dropdown */}
                  {showTagDropdown && (
                    <div
                      className="absolute left-0 top-7 z-50 min-w-[180px] max-h-[200px] overflow-y-auto rounded-xl border border-border bg-popover shadow-lg py-1"
                      data-testid="lead-tag-dropdown"
                    >
                      {unassignedTags.length === 0 ? (
                        <div className="px-3 py-2 text-[12px] text-muted-foreground">
                          {availableTags.length === 0 ? "No tags available" : "All tags already assigned"}
                        </div>
                      ) : (
                        unassignedTags.map((tag) => (
                          <button
                            key={tag.id}
                            type="button"
                            onClick={() => handleAddTag(tag)}
                            className="w-full flex items-center gap-2 px-3 py-1.5 text-[12px] text-left hover:bg-muted/50 transition-colors"
                            data-testid={`lead-tag-option-${tag.id}`}
                          >
                            <Tag className="h-3 w-3 shrink-0 text-muted-foreground" />
                            <span className="truncate">{tag.name}</span>
                            {tag.category && (
                              <span className="ml-auto text-[10px] text-muted-foreground shrink-0">{tag.category}</span>
                            )}
                          </button>
                        ))
                      )}
                    </div>
                  )}
                </div>

                {leadTags.length === 0 && !showTagDropdown && (
                  <span className="text-[12px] text-muted-foreground italic">No tags assigned</span>
                )}
              </div>
            )}
          </div>

          {/* Interaction Timeline */}
          <SectionTitle
            icon={<MessageSquare className="h-3.5 w-3.5" />}
            title={interactions.length > 0 ? `Timeline (${interactions.length})` : "Timeline"}
          />
          <div
            className="rounded-xl border border-border/40 bg-muted/20 overflow-hidden"
            data-testid="lead-detail-panel-interactions"
          >
            {loadingInteractions ? (
              <div className="flex items-center justify-center py-6 gap-2 text-muted-foreground text-[12px]">
                <Loader2 className="h-4 w-4 animate-spin" />
                Loading…
              </div>
            ) : interactions.length === 0 ? (
              <div className="py-4 px-3 text-[12px] text-muted-foreground text-center" data-testid="lead-detail-panel-no-interactions">
                No interactions yet
              </div>
            ) : (
              <div
                className="max-h-[320px] overflow-y-auto divide-y divide-border/20"
                data-testid="interaction-timeline"
              >
                {interactions.map((m, idx) => {
                  const outbound = String(m.direction || "").toLowerCase() === "outbound";
                  const isAI = Boolean(m.ai_generated);
                  const isHuman = Boolean(m.is_manual_follow_up) || (!isAI && outbound);
                  const isBump = Boolean(m.is_bump);
                  // Resolve content from uppercase or lowercase field
                  const msgContent = m.Content || m.content || "";
                  const who = m.Who || m.who || "";

                  return (
                    <div
                      key={m.id}
                      className={cn(
                        "px-3 py-2.5 transition-colors",
                        outbound
                          ? isAI
                            ? "bg-blue-500/[0.03] hover:bg-blue-500/[0.07]"
                            : "bg-purple-500/[0.03] hover:bg-purple-500/[0.07]"
                          : "hover:bg-muted/30"
                      )}
                      data-testid={`lead-detail-interaction-${m.id}`}
                      data-index={idx}
                      data-direction={m.direction}
                      data-ai-generated={isAI ? "true" : "false"}
                    >
                      {/* Row 1: direction badge + sender indicator + timestamp */}
                      <div className="flex items-center justify-between gap-2 mb-1">
                        <div className="flex items-center gap-1.5 min-w-0">
                          {/* Direction label */}
                          <span
                            className={cn(
                              "text-[10px] font-bold uppercase tracking-wide shrink-0",
                              outbound
                                ? "text-brand-blue"
                                : "text-emerald-600 dark:text-emerald-400"
                            )}
                            data-testid={`interaction-direction-${m.id}`}
                          >
                            {outbound ? "↑ Sent" : "↓ Received"}
                          </span>

                          {/* AI indicator badge */}
                          {isAI && (
                            <span
                              className="inline-flex items-center gap-0.5 px-1.5 py-px rounded-full text-[9px] font-semibold bg-blue-500/15 text-blue-600 dark:text-blue-400 shrink-0"
                              data-testid={`interaction-ai-badge-${m.id}`}
                              title="AI-generated message"
                            >
                              <Bot className="h-2.5 w-2.5" />
                              AI
                            </span>
                          )}

                          {/* Human agent indicator badge */}
                          {isHuman && !isAI && outbound && (
                            <span
                              className="inline-flex items-center gap-0.5 px-1.5 py-px rounded-full text-[9px] font-semibold bg-purple-500/15 text-purple-600 dark:text-purple-400 shrink-0"
                              data-testid={`interaction-human-badge-${m.id}`}
                              title="Sent by human agent"
                            >
                              <User className="h-2.5 w-2.5" />
                              Human
                            </span>
                          )}

                          {/* Bump indicator */}
                          {isBump && (
                            <span
                              className="inline-flex items-center px-1.5 py-px rounded-full text-[9px] font-semibold bg-amber-400/20 text-amber-600 dark:text-amber-400 shrink-0"
                              data-testid={`interaction-bump-badge-${m.id}`}
                              title="Automated bump message"
                            >
                              Bump
                            </span>
                          )}

                          {/* Type badge (SMS, Email, etc.) */}
                          {m.type && m.type !== "SMS" && (
                            <span className="text-[9px] text-muted-foreground/70 shrink-0">
                              {m.type}
                            </span>
                          )}
                        </div>

                        {/* Timestamp */}
                        <span
                          className="text-[10px] text-muted-foreground shrink-0 tabular-nums"
                          data-testid={`interaction-timestamp-${m.id}`}
                        >
                          {fmtDateTime(m.created_at)}
                        </span>
                      </div>

                      {/* Row 2: message content */}
                      <p
                        className={cn(
                          "text-[12px] leading-snug",
                          outbound ? "text-foreground" : "text-foreground/80"
                        )}
                        data-testid={`interaction-content-${m.id}`}
                      >
                        {msgContent || <span className="text-muted-foreground italic">—</span>}
                      </p>

                      {/* Row 3: sender name (if available) */}
                      {who && (
                        <p className="mt-0.5 text-[10px] text-muted-foreground/60">
                          via {who}
                        </p>
                      )}
                    </div>
                  );
                })}
              </div>
            )}
          </div>

          {/* Campaign / Account */}
          <SectionTitle icon={<Tag className="h-3.5 w-3.5" />} title="Assignment" />
          <div className="rounded-xl border border-border/40 bg-muted/20 px-3 py-1.5 mb-6">
            <InfoRow label="Account" value={lead.Account || lead.account_id} />
            <InfoRow label="Campaign" value={lead.Campaign || lead.campaign_id} />
            <InfoRow label="Created" value={fmtDate(lead.created_at)} />
          </div>
        </div>
      </SheetContent>
    </Sheet>
  );
}
