import { useState, useEffect, useRef, useCallback, useMemo } from "react";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetDescription,
} from "@/components/ui/sheet";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { apiFetch } from "@/lib/apiUtils";
import { renderRichText } from "@/lib/richTextUtils";
import { cn } from "@/lib/utils";
import {
  Phone,
  Mail,
  User,
  MessageSquare,
  Calendar,
  Tag,
  Activity,
  Bot,
  StickyNote,
  ExternalLink,
  Loader2,
  Globe,
  ArrowUpCircle,
  BarChart2,
  CheckCircle2,
  X,
  Plus,
  Save,
  Send,
  Smile,
  Meh,
  Frown,
  Layers,
  PhoneCall,
  UserCheck,
  UserX,
  RefreshCw,
  Pencil,
  Ban,
  Mic,
  Square,
  RotateCcw,
  Trash2,
  Zap,
} from "lucide-react";
import { useScoreBreakdown, TIER_COLORS, TIER_ARC_COLOR, TrendIcon } from "@/hooks/useScoreBreakdown";
import { useLocation } from "wouter";
import { useToast } from "@/hooks/use-toast";
import { useTranslation } from "react-i18next";
import { useWorkspace } from "@/hooks/useWorkspace";
import { formatBookedDate } from "@/features/leads/components/cardView/formatUtils";

// ── Types ──────────────────────────────────────────────────────────────────

export interface LeadDetailPanelProps {
  lead: Record<string, any> | null;
  open: boolean;
  onClose: () => void;
}

interface Interaction {
  id: number;
  lead_id?: number;
  Leads_id?: number;
  direction: string;
  /** DB column is uppercase "Content" — API returns this form */
  Content?: string;
  /** fallback lowercase form */
  content?: string;
  created_at?: string;
  type?: string;
  /** DB column is uppercase "Who" — AI agent name or sender identifier */
  Who?: string;
  who?: string;
  /** true when the message was generated by AI */
  ai_generated?: boolean;
  /** true when a human agent manually sent this message */
  is_manual_follow_up?: boolean;
  is_bump?: boolean;
  triggered_by?: string;
  status?: string;
  sentiment_detected?: string;
}

interface TagData {
  id: number;
  name: string;
  color?: string | null;
  category?: string | null;
  slug?: string | null;
}

interface LeadTagEntry {
  id?: number;
  tagsId?: number;
  Tags_id?: number;
  leadsId?: number;
  Leads_id?: number;
  tagName?: string | null;
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function fmtDate(s: string | null | undefined): string {
  if (!s) return "—";
  try {
    return new Date(s).toLocaleDateString(undefined, {
      day: "2-digit",
      month: "short",
      year: "numeric",
    });
  } catch {
    return s;
  }
}

function fmtDateTime(s: string | null | undefined): string {
  if (!s) return "—";
  try {
    return new Date(s).toLocaleString(undefined, {
      day: "2-digit",
      month: "short",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  } catch {
    return s;
  }
}

const STATUS_COLORS: Record<string, { bg: string; text: string }> = {
  New: { bg: "bg-gray-500/15", text: "text-gray-600 dark:text-gray-400" },
  Contacted: { bg: "bg-indigo-600/15", text: "text-indigo-600 dark:text-indigo-400" },
  Responded: { bg: "bg-teal-500/15", text: "text-teal-600 dark:text-teal-400" },
  "Multiple Responses": { bg: "bg-green-500/15", text: "text-green-600 dark:text-green-400" },
  Qualified: { bg: "bg-lime-500/15", text: "text-lime-600 dark:text-lime-400" },
  Booked: { bg: "bg-amber-400/20", text: "text-amber-600 dark:text-amber-400" },
  Closed: { bg: "bg-emerald-500/15", text: "text-emerald-600 dark:text-emerald-400" },
  Lost: { bg: "bg-red-500/15", text: "text-red-600 dark:text-red-400" },
  DND: { bg: "bg-zinc-500/15", text: "text-zinc-600 dark:text-zinc-400" },
};

const PRIORITY_COLORS: Record<string, { bg: string; text: string; ring: string }> = {
  High: { bg: "bg-red-500/15", text: "text-red-600 dark:text-red-400", ring: "ring-1 ring-red-500/30" },
  Medium: { bg: "bg-amber-400/20", text: "text-amber-600 dark:text-amber-400", ring: "ring-1 ring-amber-400/30" },
  Low: { bg: "bg-emerald-500/15", text: "text-emerald-600 dark:text-emerald-400", ring: "ring-1 ring-emerald-500/30" },
};

function StatusBadge({ label }: { label: string }) {
  const colors = STATUS_COLORS[label] ?? { bg: "bg-muted", text: "text-muted-foreground" };
  return (
    <span
      className={cn(
        "inline-flex items-center px-2 py-0.5 rounded-full text-[11px] font-semibold",
        colors.bg,
        colors.text
      )}
    >
      {label}
    </span>
  );
}

function PriorityBadge({ priority }: { priority: string }) {
  const colors = PRIORITY_COLORS[priority] ?? {
    bg: "bg-muted",
    text: "text-muted-foreground",
    ring: "ring-1 ring-border/30",
  };
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[11px] font-semibold",
        colors.bg,
        colors.text,
        colors.ring
      )}
      data-testid="lead-detail-priority-badge"
      data-priority={priority}
    >
      <ArrowUpCircle className="h-3 w-3 shrink-0" />
      {priority}
    </span>
  );
}

function InfoRow({
  icon,
  label,
  value,
  mono = false,
}: {
  icon?: React.ReactNode;
  label: string;
  value: React.ReactNode;
  mono?: boolean;
}) {
  return (
    <div className="flex items-start justify-between gap-3 py-1.5 border-b border-border/30 last:border-0">
      <div className="flex items-center gap-1.5 shrink-0">
        {icon && <span className="text-muted-foreground/60">{icon}</span>}
        <span className="text-[11px] text-muted-foreground">{label}</span>
      </div>
      <span
        className={cn(
          "text-[12px] text-foreground text-right break-words max-w-[58%]",
          mono && "font-mono text-[11px]"
        )}
      >
        {value || "—"}
      </span>
    </div>
  );
}

function SectionTitle({ icon, title }: { icon: React.ReactNode; title: string }) {
  return (
    <div className="flex items-center gap-2 mb-2 mt-4 first:mt-0">
      <div className="icon-circle-lg border-2 border-border/25 text-muted-foreground flex items-center justify-center shrink-0">{icon}</div>
      <h3 className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
        {title}
      </h3>
    </div>
  );
}

// ── Pipeline Stages ────────────────────────────────────────────────────────

const PIPELINE_STAGES = [
  "New",
  "Contacted",
  "Responded",
  "Multiple Responses",
  "Qualified",
  "Booked",
  "Closed",
  "Lost",
  "DND",
] as const;

// ── Sentiment Badge ────────────────────────────────────────────────────────

const SENTIMENT_CONFIG: Record<string, { bg: string; text: string; icon: React.ReactNode }> = {
  positive: {
    bg: "bg-emerald-500/15",
    text: "text-emerald-600 dark:text-emerald-400",
    icon: <Smile className="h-3 w-3" />,
  },
  negative: {
    bg: "bg-red-500/15",
    text: "text-red-600 dark:text-red-400",
    icon: <Frown className="h-3 w-3" />,
  },
  neutral: {
    bg: "bg-zinc-500/15",
    text: "text-zinc-600 dark:text-zinc-400",
    icon: <Meh className="h-3 w-3" />,
  },
};

function SentimentBadge({ sentiment }: { sentiment: string }) {
  const key = sentiment?.toLowerCase() ?? "";
  const config = SENTIMENT_CONFIG[key] ?? {
    bg: "bg-muted",
    text: "text-muted-foreground",
    icon: <Meh className="h-3 w-3" />,
  };
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1.5 px-2 py-0.5 rounded-full text-[11px] font-semibold capitalize",
        config.bg,
        config.text
      )}
      data-testid="ai-sentiment-badge"
      data-sentiment={key}
    >
      {config.icon}
      {sentiment}
    </span>
  );
}

// ── AI Memory Display ──────────────────────────────────────────────────────

function formatAiMemory(raw: string): string {
  if (!raw) return "";
  // Try to parse as JSON and pretty-print
  try {
    const parsed = JSON.parse(raw);
    if (typeof parsed === "object" && parsed !== null) {
      // Format key-value pairs as readable lines
      return Object.entries(parsed)
        .map(([k, v]) => {
          const label = k.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
          const value = typeof v === "object" ? JSON.stringify(v, null, 2) : String(v);
          return `${label}: ${value}`;
        })
        .join("\n");
    }
    return typeof parsed === "string" ? parsed : JSON.stringify(parsed, null, 2);
  } catch {
    return raw; // return as-is if not JSON
  }
}

// ── Inline Edit Field ──────────────────────────────────────────────────────

interface InlineEditFieldProps {
  label: string;
  value: string;
  onSave: (newValue: string) => Promise<void>;
  icon?: React.ReactNode;
  type?: "text" | "email" | "tel";
  testId?: string;
  selectOptions?: string[];
}

function InlineEditField({
  label,
  value,
  onSave,
  icon,
  type = "text",
  testId,
  selectOptions,
}: InlineEditFieldProps) {
  const [editing, setEditing] = useState(false);
  const [localValue, setLocalValue] = useState(value);
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);

  // Sync if parent value changes
  useEffect(() => {
    if (!editing) setLocalValue(value);
  }, [value, editing]);

  const handleStartEdit = () => {
    setLocalValue(value);
    setEditing(true);
    setSaved(false);
    setTimeout(() => inputRef.current?.focus(), 0);
  };

  const handleSave = async () => {
    if (localValue === value) {
      setEditing(false);
      return;
    }
    setSaving(true);
    try {
      await onSave(localValue);
      setSaved(true);
      setTimeout(() => setSaved(false), 2000);
    } finally {
      setSaving(false);
      setEditing(false);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter") { e.preventDefault(); handleSave(); }
    if (e.key === "Escape") { setLocalValue(value); setEditing(false); }
  };

  return (
    <div
      className="flex items-center justify-between gap-3 py-1.5 border-b border-border/30 last:border-0 group"
      data-testid={testId}
    >
      <div className="flex items-center gap-1.5 shrink-0">
        {icon && <span className="text-muted-foreground/60">{icon}</span>}
        <span className="text-[11px] text-muted-foreground">{label}</span>
      </div>

      {editing ? (
        <div className="flex items-center gap-1 flex-1 min-w-0 justify-end">
          {selectOptions ? (
            <select
              value={localValue}
              onChange={(e) => setLocalValue(e.target.value)}
              onBlur={handleSave}
              className="text-[12px] bg-background border border-border rounded px-1.5 py-0.5 max-w-[140px] focus:outline-none focus:ring-1 focus:ring-brand-indigo/50"
              data-testid={`${testId}-select`}
              autoFocus
            >
              {selectOptions.map((opt) => (
                <option key={opt} value={opt}>{opt || "—"}</option>
              ))}
            </select>
          ) : (
            <input
              ref={inputRef}
              type={type}
              value={localValue}
              onChange={(e) => setLocalValue(e.target.value)}
              onBlur={handleSave}
              onKeyDown={handleKeyDown}
              className="text-[12px] bg-background border border-border rounded px-1.5 py-0.5 max-w-[160px] focus:outline-none focus:ring-1 focus:ring-brand-indigo/50"
              data-testid={`${testId}-input`}
              disabled={saving}
            />
          )}
          {saving && <Loader2 className="h-3 w-3 animate-spin text-muted-foreground shrink-0" />}
        </div>
      ) : (
        <div className="flex items-center gap-1.5 min-w-0">
          {saved && <CheckCircle2 className="h-3 w-3 text-emerald-500 shrink-0" />}
          <span className="text-[12px] text-foreground text-right break-words max-w-[140px] truncate">
            {value || "—"}
          </span>
          <button
            type="button"
            onClick={handleStartEdit}
            className="opacity-0 group-hover:opacity-100 transition-opacity ml-0.5 icon-circle-lg icon-circle-base hover:border-brand-indigo/40 hover:text-brand-indigo"
            aria-label={`Edit ${label}`}
            data-testid={`${testId}-edit-btn`}
          >
            <Pencil className="h-3 w-3" />
          </button>
        </div>
      )}
    </div>
  );
}

// ── Score Arc (detail panel — larger, tier-colored) ──────────────────────────

function ScoreArcPanel({ score, tier }: { score: number; tier?: string }) {
  const fillColor = (tier && TIER_ARC_COLOR[tier]) || "#4F46E5";
  const pct = Math.max(0, Math.min(100, score)) / 100;
  const cx = 100, cy = 85, r = 58, sw = 14;
  const arcLen = Math.PI * r;
  const arcPath = `M ${cx - r} ${cy} A ${r} ${r} 0 0 1 ${cx + r} ${cy}`;

  return (
    <svg viewBox="0 0 200 100" className="w-full max-w-[170px] shrink-0">
      <path d={arcPath} fill="none" stroke="currentColor" className="text-muted" strokeWidth={sw} strokeLinecap="round" />
      {pct > 0 && (
        <path
          d={arcPath}
          fill="none"
          stroke={fillColor}
          strokeWidth={sw}
          strokeLinecap="round"
          strokeDasharray={`${arcLen}`}
          strokeDashoffset={`${arcLen * (1 - pct)}`}
        />
      )}
      <text x={cx} y={cy - 12} textAnchor="middle" dominantBaseline="central"
        className="fill-gray-900 dark:fill-gray-100"
        style={{ fontSize: 34, fontWeight: 900, letterSpacing: -2 }}>
        {score}
      </text>
      <text x={cx} y={cy + 6} textAnchor="middle" dominantBaseline="central"
        className="fill-muted-foreground"
        style={{ fontSize: 11, fontWeight: 500 }}>
        out of 100
      </text>
    </svg>
  );
}

// ── Score Detail Bar (with context line) ─────────────────────────────────────

function ScoreDetailBar({ label, rawScore, weight, maxRaw, context }: {
  label: string; rawScore: number; weight: number; maxRaw: number; context?: string
}) {
  const contribution = Math.round(weight * Math.max(0, Math.min(maxRaw, rawScore)));
  const maxContrib = Math.round(weight * maxRaw);
  const pct = maxContrib > 0 ? (contribution / maxContrib) * 100 : 0;
  const textColor = pct >= 70 ? "text-emerald-600 dark:text-emerald-400" : pct >= 40 ? "text-amber-600 dark:text-amber-400" : "text-muted-foreground";

  // Segmented bar: one segment per 6 contribution points (5 segments for /30, 6 for /36)
  const CHUNK = 6;
  const numChunks = Math.round(maxContrib / CHUNK);
  const filledChunks = maxContrib > 0 ? (contribution / maxContrib) * numChunks : 0;

  return (
    <div className="flex flex-col gap-1">
      <div className="flex items-center justify-between">
        <span className="text-[12px] font-medium text-foreground">{label}</span>
        <span className={cn("text-[13px] font-bold tabular-nums", textColor)}>
          {contribution}
          <span className="text-[10px] font-normal text-muted-foreground ml-0.5">/{maxContrib}</span>
        </span>
      </div>
      <div className="flex gap-1">
        {Array.from({ length: numChunks }).map((_, i) => {
          const fill = Math.min(1, Math.max(0, filledChunks - i));
          const segColor = pct >= 70 ? "bg-emerald-500" : pct >= 40 ? "bg-amber-400" : "bg-brand-indigo/70";
          return (
            <div key={i} className="relative flex-1 h-2 rounded-sm bg-muted overflow-hidden">
              {fill > 0 && (
                <div
                  className={cn("absolute inset-y-0 left-0 rounded-sm transition-[width] duration-500", segColor)}
                  style={{ width: `${fill * 100}%` }}
                />
              )}
            </div>
          );
        })}
      </div>
      {context && (
        <span className="text-[11px] text-muted-foreground leading-snug">{context}</span>
      )}
    </div>
  );
}

// ── Score context helpers ────────────────────────────────────────────────────

function engagementContext(lead: Record<string, any> | null): string {
  if (!lead) return "";
  const parts: string[] = [];

  // Reply recency
  const lastReceived = lead.lastMessageReceivedAt ?? lead.last_message_received_at;
  if (lastReceived) {
    const hours = (Date.now() - new Date(lastReceived).getTime()) / 3600000;
    if (hours < 1) parts.push("Replied just now");
    else if (hours < 24) parts.push(`Replied ${Math.round(hours)}h ago`);
    else {
      const days = Math.floor(hours / 24);
      parts.push(days === 1 ? "Replied yesterday" : `Replied ${days}d ago`);
      if (days >= 7) parts.push("Score decaying");
    }
  } else {
    parts.push("No replies yet");
  }

  // Sentiment
  const sentiment = (lead.aiSentiment ?? lead.ai_sentiment ?? "").toString().toLowerCase();
  if (sentiment === "positive") parts.push("Positive sentiment");
  else if (sentiment === "neutral") parts.push("Neutral sentiment");
  else if (sentiment === "negative") parts.push("Negative sentiment");

  // Intent signals
  const intentRaw = (lead.aiIntentSignals ?? lead.ai_intent_signals ?? "").toString();
  if (intentRaw) {
    const intents = intentRaw.split(",").map((s: string) => s.trim().toLowerCase()).filter(Boolean);
    const labels: Record<string, string> = {
      asked_pricing: "Asked pricing",
      mentioned_timeline: "Has timeline",
      requested_callback: "Wants callback",
      asked_features: "Asked features",
      expressed_objection: "Objection raised",
      not_interested: "Not interested",
    };
    for (const intent of intents) {
      if (labels[intent]) { parts.push(labels[intent]); break; }
    }
  }

  // Bump stage penalty
  const bumpStage = Number(lead.currentBumpStage ?? lead.current_bump_stage ?? 0);
  if (bumpStage >= 2) parts.push(`Bumped ${bumpStage}x, no reply`);

  return parts.join(" · ");
}

function activityContext(lead: Record<string, any> | null): string {
  if (!lead) return "";
  const received = Number(lead.messageCountReceived ?? lead.message_count_received ?? 0);
  const sent = Number(lead.messageCountSent ?? lead.message_count_sent ?? 0);
  const parts: string[] = [];
  parts.push(`${received} ${received === 1 ? "reply" : "replies"} received`);
  if (sent > 0 && received > 0) {
    const ratio = Math.round((received / sent) * 100);
    parts.push(`${ratio}% reply rate`);
  } else if (sent > 0 && received === 0) {
    parts.push("No replies yet");
  }

  // Message frequency
  const firstSent = lead.firstMessageSentAt ?? lead.first_message_sent_at;
  if (firstSent && received >= 2) {
    const daysSinceFirst = (Date.now() - new Date(firstSent).getTime()) / 86400000;
    if (daysSinceFirst >= 1) {
      const perDay = received / daysSinceFirst;
      if (perDay >= 1) parts.push(`~${Math.round(perDay)}/day`);
      else parts.push(`~${Math.round(perDay * 7)}/week`);
    }
  }

  return parts.join(" · ");
}

const FUNNEL_STAGE_ORDER = [
  "New", "Queued", "Contacted", "Responded", "Multiple Responses",
  "Qualified", "Booked", "Closed", "DND", "Lost",
];

const FUNNEL_NEXT_ACTION: Record<string, string> = {
  New: "Waiting to be contacted",
  Queued: "Queued for outreach",
  Contacted: "Waiting for first reply",
  Responded: "Engage to qualify",
  "Multiple Responses": "Ready to qualify",
  Qualified: "Schedule a call",
  Booked: "Call scheduled",
  Closed: "Deal closed",
  DND: "Do not contact",
  Lost: "Lead lost",
};

function funnelContext(lead: Record<string, any> | null): string {
  if (!lead) return "";
  const status = lead.conversionStatus ?? lead.conversion_status ?? lead.Conversion_Status ?? "";
  if (!status) return "Not set";

  const parts: string[] = [];

  // Next action hint
  const hint = FUNNEL_NEXT_ACTION[status];
  if (hint) parts.push(hint);

  // Time at current stage
  const lastActivity = lead.last_interaction_at ?? lead.lastMessageReceivedAt ?? lead.last_message_received_at ?? lead.lastMessageSentAt ?? lead.last_message_sent_at;
  if (lastActivity) {
    const days = Math.floor((Date.now() - new Date(lastActivity).getTime()) / 86400000);
    if (days >= 1) parts.push(`${days}d at this stage`);
  }

  return parts.join(" · ");
}

// ── Main Component ────────────────────────────────────────────────────────

export function LeadDetailPanel({ lead, open, onClose }: LeadDetailPanelProps) {
  const { t } = useTranslation("leads");
  const { accounts } = useWorkspace();
  const accountTimezone = useMemo(() => {
    if (!lead) return undefined;
    const aid = lead.account_id ?? lead.accounts_id;
    const acct = accounts.find((a: any) => a.id === Number(aid));
    return (acct?.timezone as string) || undefined;
  }, [lead, accounts]);
  const [, setLocation] = useLocation();
  const [interactions, setInteractions] = useState<Interaction[]>([]);
  const [loadingInteractions, setLoadingInteractions] = useState(false);
  const [tagEvents, setTagEvents] = useState<any[]>([]);
  const [localStatus, setLocalStatus] = useState<string>("");
  const [savingStatus, setSavingStatus] = useState(false);
  const [stageSaved, setStageSaved] = useState(false);
  const [localAiSummary, setLocalAiSummary] = useState<string | null>(null);

  // ── Tags state ──
  const [leadTags, setLeadTags] = useState<TagData[]>([]);
  const [availableTags, setAvailableTags] = useState<TagData[]>([]);
  const [loadingTags, setLoadingTags] = useState(false);
  const [addingTag, setAddingTag] = useState(false);
  const [removingTagId, setRemovingTagId] = useState<number | null>(null);
  const [showTagDropdown, setShowTagDropdown] = useState(false);

  // ── Score breakdown ──
  const { breakdown: scoreBreakdown, loading: scoreLoading, refetch: refetchScore, resetToZero: resetScoreToZero } = useScoreBreakdown(lead?.id ?? null);
  const panelScore = scoreBreakdown?.lead_score ?? (lead?.lead_score ?? lead?.leadScore ?? 0);

  // ── Notes editing state ──
  const [localNotes, setLocalNotes] = useState<string>("");
  const [notesDirty, setNotesDirty] = useState(false);
  const [savingNotes, setSavingNotes] = useState(false);
  const [notesSaved, setNotesSaved] = useState(false);
  const notesOriginalRef = useRef<string>("");

  // ── Voice recording state ──
  const [isRecordingVoice, setIsRecordingVoice] = useState(false);
  const [recordingSeconds, setRecordingSeconds] = useState(0);
  const mediaRecorderRef = useRef<MediaRecorder | null>(null);
  const recordingChunksRef = useRef<Blob[]>([]);
  const recordingTimerRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const [transcribing, setTranscribing] = useState(false);

  const { toast } = useToast();

  // ── Manual takeover toggle state ──
  const [localManualTakeover, setLocalManualTakeover] = useState<boolean>(false);
  const [savingManualTakeover, setSavingManualTakeover] = useState(false);

  // ── DNC / Opted-out state ──
  const [localOptedOut, setLocalOptedOut] = useState<boolean>(false);
  const [localDncReason, setLocalDncReason] = useState<string>("");
  const [savingDnc, setSavingDnc] = useState(false);
  const [dncSaved, setDncSaved] = useState(false);
  const [showDncReason, setShowDncReason] = useState(false);

  const leadId = lead?.Id || lead?.id;

  // Sync localStatus when lead changes
  useEffect(() => {
    const status = lead?.conversion_status || lead?.Conversion_Status || "";
    setLocalStatus(status);
    setStageSaved(false);
  }, [lead?.Id, lead?.id, lead?.Conversion_Status, lead?.conversion_status]);

  // Sync notes when lead changes
  useEffect(() => {
    const notes = lead?.notes || "";
    notesOriginalRef.current = notes;
    setLocalNotes(notes);
    setNotesDirty(false);
    setNotesSaved(false);
  }, [lead?.Id, lead?.id, lead?.notes]);

  // Cleanup voice recording on unmount
  useEffect(() => {
    return () => {
      if (recordingTimerRef.current) clearInterval(recordingTimerRef.current);
      if (mediaRecorderRef.current) { try { mediaRecorderRef.current.stop(); } catch {} }
    };
  }, []);

  // Sync manual_takeover when lead changes
  useEffect(() => {
    setLocalManualTakeover(Boolean(lead?.manual_takeover));
  }, [lead?.Id, lead?.id, lead?.manual_takeover]);

  // Sync DNC / opted-out state when lead changes
  useEffect(() => {
    const optedOut = Boolean(lead?.opted_out);
    setLocalOptedOut(optedOut);
    setLocalDncReason(lead?.dnc_reason || "");
    setShowDncReason(optedOut);
    setDncSaved(false);
  }, [lead?.Id, lead?.id, lead?.opted_out, lead?.dnc_reason]);

  // Fetch interactions when panel opens with a lead
  useEffect(() => {
    if (!open || !leadId) {
      setInteractions([]);
      return;
    }

    let cancelled = false;
    setLoadingInteractions(true);

    // Fetch all interactions — no limit query param (API returns all when no ?page= given)
    apiFetch(`/api/interactions?leadId=${leadId}`)
      .then((r) => r.ok ? r.json() : null)
      .then((data) => {
        if (cancelled) return;
        const list: Interaction[] = Array.isArray(data) ? data : data?.list || data?.data || [];
        // Sort chronologically ascending (oldest first) — API returns DESC by default
        list.sort((a, b) => {
          const ta = a.created_at ? new Date(a.created_at).getTime() : 0;
          const tb = b.created_at ? new Date(b.created_at).getTime() : 0;
          return ta - tb;
        });
        setInteractions(list);
      })
      .catch(() => {
        if (!cancelled) setInteractions([]);
      })
      .finally(() => {
        if (!cancelled) setLoadingInteractions(false);
      });

    return () => { cancelled = true; };
  }, [open, leadId]);

  // Fetch tag events for inline timeline chips
  useEffect(() => {
    if (!open || !leadId) { setTagEvents([]); return; }
    let cancelled = false;
    apiFetch(`/api/leads/${leadId}/tag-events`)
      .then(r => r.ok ? r.json() : [])
      .then(data => { if (!cancelled) setTagEvents(Array.isArray(data) ? data : []); })
      .catch(() => { if (!cancelled) setTagEvents([]); });
    return () => { cancelled = true; };
  }, [open, leadId]);

  // ── Fetch lead tags when panel opens ──
  useEffect(() => {
    if (!open || !leadId) {
      setLeadTags([]);
      setShowTagDropdown(false);
      return;
    }

    let cancelled = false;
    setLoadingTags(true);

    // Fetch lead's current tags (returns Leads_Tags rows with tagName denormalized)
    apiFetch(`/api/leads/${leadId}/tags`)
      .then((r) => r.ok ? r.json() : [])
      .then((data: LeadTagEntry[]) => {
        if (cancelled) return;
        const arr = Array.isArray(data) ? data : [];
        // Convert LeadTagEntry rows to TagData for display
        // The Leads_Tags table has a tagName denormalized field
        const tagList: TagData[] = arr
          .filter((e) => e.tagsId || e.Tags_id)
          .map((e) => ({
            id: e.tagsId ?? e.Tags_id ?? 0,
            name: e.tagName || `Tag #${e.tagsId ?? e.Tags_id}`,
            color: null,
            category: null,
          }));
        setLeadTags(tagList);
      })
      .catch(() => { if (!cancelled) setLeadTags([]); })
      .finally(() => { if (!cancelled) setLoadingTags(false); });

    return () => { cancelled = true; };
  }, [open, leadId]);

  // ── Fetch available tags once ──
  useEffect(() => {
    if (!open) return;
    apiFetch("/api/tags")
      .then((r) => r.ok ? r.json() : Promise.resolve([]))
      .then((data: any) => {
        const arr: any[] = Array.isArray(data) ? data : data?.list || data?.data || [];
        setAvailableTags(arr.map((t: any) => ({
          id: t.Id ?? t.id,
          name: t.Name ?? t.name ?? "Tag",
          color: t.Color ?? t.color ?? null,
          category: t.Category ?? t.category ?? null,
          slug: t.Slug ?? t.slug ?? null,
        })));
      })
      .catch(() => {});
  }, [open]);

  const handleAddTag = async (tag: TagData) => {
    if (!leadId) return;
    // Already assigned?
    if (leadTags.some((t) => t.id === tag.id)) {
      setShowTagDropdown(false);
      return;
    }
    setAddingTag(true);
    try {
      const res = await apiFetch(`/api/leads/${leadId}/tags`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ tagId: tag.id }),
      });
      if (res.ok) {
        setLeadTags((prev) => [...prev, tag]);
      }
    } catch {
      // silently ignore
    } finally {
      setAddingTag(false);
      setShowTagDropdown(false);
    }
  };

  const handleRemoveTag = async (tagId: number) => {
    if (!leadId) return;
    setRemovingTagId(tagId);
    try {
      const res = await apiFetch(`/api/leads/${leadId}/tags/${tagId}`, {
        method: "DELETE",
      });
      if (res.ok) {
        setLeadTags((prev) => prev.filter((t) => t.id !== tagId));
      }
    } catch {
      // silently ignore
    } finally {
      setRemovingTagId(null);
    }
  };

  // ── Campaigns state (filtered by lead's account, agency view only) ──
  const isAgencyPanel = window.location.pathname.startsWith("/agency");
  const leadAccountId = Number(lead?.Accounts_id || lead?.account_id || lead?.accounts_id || 0);
  const [campaigns, setCampaigns] = useState<{ id: number; name: string }[]>([]);

  useEffect(() => {
    if (!open || !isAgencyPanel) return;
    apiFetch("/api/campaigns")
      .then((r) => r.ok ? r.json() : Promise.resolve([]))
      .then((data: any) => {
        const arr: any[] = Array.isArray(data) ? data : data?.list || data?.data || [];
        const mapped = arr.map((c: any) => ({
          id: c.Id ?? c.id,
          name: c.Name ?? c.name ?? `Campaign #${c.Id ?? c.id}`,
          accountId: Number(c.Accounts_id ?? c.accounts_id ?? c.account_id ?? 0),
        }));
        // Filter to only campaigns belonging to this lead's account
        const filtered = leadAccountId
          ? mapped.filter((c) => c.accountId === leadAccountId)
          : mapped;
        setCampaigns(filtered.map(({ id, name }) => ({ id, name })));
      })
      .catch(() => {});
  }, [open, isAgencyPanel, leadAccountId]);

  // Derive available tags that aren't yet assigned
  const unassignedTags = availableTags.filter(
    (t) => !leadTags.some((lt) => lt.id === t.id)
  );

  const handleStageChange = async (newStage: string) => {
    if (!leadId || newStage === localStatus) return;

    const prevStatus = localStatus;
    setLocalStatus(newStage); // optimistic update
    setSavingStatus(true);
    setStageSaved(false);

    try {
      const res = await apiFetch(`/api/leads/${leadId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ Conversion_Status: newStage }),
      });
      if (!res.ok) {
        setLocalStatus(prevStatus); // revert on error
      } else {
        setStageSaved(true);
        setTimeout(() => setStageSaved(false), 2000);
        // After booking/closing, the Python engine generates an AI summary async.
        // Refetch the lead after ~3.5s to pick it up without requiring a page refresh.
        if (["Booked", "Closed"].includes(newStage)) {
          setTimeout(async () => {
            try {
              const r = await apiFetch(`/api/leads/${leadId}`);
              if (r.ok) {
                const updated = await r.json();
                if (updated.ai_summary) setLocalAiSummary(updated.ai_summary);
              }
            } catch { /* silent */ }
          }, 3500);
        }
      }
    } catch {
      setLocalStatus(prevStatus); // revert on error
    } finally {
      setSavingStatus(false);
    }
  };

  const handleNotesSave = async () => {
    if (!leadId || !notesDirty || savingNotes) return;
    setSavingNotes(true);
    setNotesSaved(false);
    try {
      const res = await apiFetch(`/api/leads/${leadId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ notes: localNotes }),
      });
      if (res.ok) {
        notesOriginalRef.current = localNotes;
        setNotesDirty(false);
        setNotesSaved(true);
        setTimeout(() => setNotesSaved(false), 2000);
      }
    } catch {
      // silently fail — user can retry
    } finally {
      setSavingNotes(false);
    }
  };

  const startVoiceRecording = useCallback(async () => {
    if (!leadId) return;
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      const mr = new MediaRecorder(stream, {
        mimeType: MediaRecorder.isTypeSupported("audio/webm;codecs=opus")
          ? "audio/webm;codecs=opus" : "audio/webm",
      });
      recordingChunksRef.current = [];
      mr.ondataavailable = (e) => {
        if (e.data.size > 0) recordingChunksRef.current.push(e.data);
      };
      mr.onstop = async () => {
        stream.getTracks().forEach((t) => t.stop());
        const blob = new Blob(recordingChunksRef.current, { type: mr.mimeType });
        const reader = new FileReader();
        reader.onloadend = async () => {
          const dataUrl = reader.result as string;
          setTranscribing(true);
          try {
            console.log("[voice] Sending audio:", dataUrl.length, "chars, mime:", mr.mimeType);
            const httpRes = await apiFetch(`/api/leads/${leadId}/transcribe-voice`, {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({ audio_data: dataUrl, mime_type: mr.mimeType }),
            });
            const res = await httpRes.json() as any;
            if (!httpRes.ok || res.error) {
              const desc = res.error === "NO_GROQ_API_KEY"
                ? "Groq API key not configured."
                : res.detail || res.error || t("toast.networkError");
              console.error("[voice] Transcription error:", res);
              toast({
                title: t("toast.transcriptionFailed"),
                description: String(desc).slice(0, 200),
                variant: "destructive",
              });
              return;
            }
            if (res.transcription) {
              setLocalNotes((prev) => {
                const separator = prev.trim() ? "\n\n" : "";
                const updated = prev + separator + res.transcription;
                setNotesDirty(updated !== notesOriginalRef.current);
                setNotesSaved(false);
                return updated;
              });
            }
          } catch {
            toast({
              title: t("toast.transcriptionFailed"),
              description: t("toast.networkError"),
              variant: "destructive",
            });
          } finally {
            setTranscribing(false);
          }
        };
        reader.readAsDataURL(blob);
      };
      mr.start(250);
      mediaRecorderRef.current = mr;
      setIsRecordingVoice(true);
      setRecordingSeconds(0);
      recordingTimerRef.current = setInterval(() => setRecordingSeconds((s) => s + 1), 1000);
    } catch {
      toast({
        title: t("toast.microphoneDenied"),
        description: t("toast.microphoneDescription"),
        variant: "destructive",
      });
    }
  }, [leadId, toast]);

  const stopVoiceRecording = useCallback(() => {
    if (recordingTimerRef.current) {
      clearInterval(recordingTimerRef.current);
      recordingTimerRef.current = null;
    }
    mediaRecorderRef.current?.stop();
    mediaRecorderRef.current = null;
    setIsRecordingVoice(false);
    setRecordingSeconds(0);
  }, []);

  const handleManualTakeoverChange = async (checked: boolean) => {
    if (!leadId || savingManualTakeover) return;
    const prev = localManualTakeover;
    setLocalManualTakeover(checked); // optimistic update
    setSavingManualTakeover(true);
    try {
      const res = await apiFetch(`/api/leads/${leadId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ manual_takeover: checked }),
      });
      if (!res.ok) {
        setLocalManualTakeover(prev); // revert on error
      }
    } catch {
      setLocalManualTakeover(prev);
    } finally {
      setSavingManualTakeover(false);
    }
  };

  // Generic inline field save handler (patches lead by field name)
  const handleInlineFieldSave = async (fieldName: string, newValue: string) => {
    if (!leadId) return;
    await apiFetch(`/api/leads/${leadId}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ [fieldName]: newValue }),
    });
  };

  const handleDncChange = async (checked: boolean) => {
    if (!leadId || savingDnc) return;
    const prev = localOptedOut;
    setLocalOptedOut(checked);
    setShowDncReason(checked);
    setSavingDnc(true);
    setDncSaved(false);
    try {
      const payload: Record<string, any> = { opted_out: checked };
      if (!checked) payload.dnc_reason = "";
      const res = await apiFetch(`/api/leads/${leadId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });
      if (!res.ok) {
        setLocalOptedOut(prev);
        setShowDncReason(prev);
      } else {
        if (!checked) setLocalDncReason("");
        setDncSaved(true);
        setTimeout(() => setDncSaved(false), 2000);
      }
    } catch {
      setLocalOptedOut(prev);
      setShowDncReason(prev);
    } finally {
      setSavingDnc(false);
    }
  };

  const handleDncReasonSave = async () => {
    if (!leadId || savingDnc) return;
    setSavingDnc(true);
    try {
      await apiFetch(`/api/leads/${leadId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ dnc_reason: localDncReason }),
      });
      setDncSaved(true);
      setTimeout(() => setDncSaved(false), 2000);
    } catch {
      // silently ignore
    } finally {
      setSavingDnc(false);
    }
  };

  if (!lead) return null;

  const fullName = lead.full_name || [lead.first_name, lead.last_name].filter(Boolean).join(" ") || "Unknown";
  const convStatus = localStatus || lead.conversion_status || lead.Conversion_Status || "";
  const autoStatus = lead.automation_status || lead.Automation_Status || "";
  const email = lead.email || lead.Email || "";
  const source = lead.Source || lead.source || lead.inquiries_source || "";
  const priority = lead.priority || lead.Priority || "";
  const isAgency = window.location.pathname.startsWith("/agency");

  // Derived engagement metrics
  const sentCount = Number(lead.message_count_sent || 0);
  const recvCount = Number(lead.message_count_received || 0);
  const responseRate = sentCount > 0 ? `${Math.round((recvCount / sentCount) * 100)}%` : "—";

  const lastActivityTs = Math.max(
    lead.last_message_sent_at ? new Date(lead.last_message_sent_at).getTime() : 0,
    lead.last_message_received_at ? new Date(lead.last_message_received_at).getTime() : 0,
  );
  const daysInactive = lastActivityTs > 0
    ? `${Math.floor((Date.now() - lastActivityTs) / 86400000)}d ago`
    : "—";

  const handleViewFull = () => {
    onClose();
    const path = isAgency ? `/agency/contacts/${leadId}` : `/subaccount/contacts/${leadId}`;
    setLocation(path);
  };

  return (
    <Sheet open={open} onOpenChange={(v) => { if (!v) onClose(); }}>
      <SheetContent
        side="right"
        className="w-full sm:w-[420px] sm:max-w-[420px] p-0 flex flex-col overflow-hidden bg-background text-foreground dark:bg-card dark:border-border"
        data-testid="lead-detail-panel"
      >
        {/* Header */}
        <SheetHeader
          className="px-4 pt-4 pb-4 border-b border-border shrink-0 md:px-5 md:pt-5"
          data-testid="lead-info-header"
        >
          {/* Row 1: label */}
          <div className="flex items-center justify-between gap-2 mb-0.5">
            <div className="text-[10px] font-semibold uppercase tracking-widest text-muted-foreground">
              {t("detail.title")}
            </div>
          </div>

          {/* Row 2: name (most prominent) */}
          <SheetTitle
            className="text-[18px] font-bold leading-tight truncate"
            data-testid="lead-detail-panel-name"
          >
            {fullName}
          </SheetTitle>

          {autoStatus && (
            <SheetDescription className="text-[11px] mt-1.5">
              {autoStatus}
            </SheetDescription>
          )}

          {/* Row 4: View full page */}
          <button
            onClick={handleViewFull}
            className="mt-2 inline-flex items-center gap-1.5 text-[11px] text-brand-indigo hover:text-brand-indigo/80 font-medium transition-colors"
            data-testid="lead-detail-panel-view-full"
          >
            <ExternalLink className="h-3 w-3" />
            {t("detail.openFullPage")}
          </button>
        </SheetHeader>

        {/* Action buttons row */}
        <div className="shrink-0 px-4 py-2.5 border-b border-border flex items-center justify-center gap-1.5 md:px-5">
          <button
            onClick={async () => {
              try {
                const res = await apiFetch(`/api/leads/${leadId}/trigger-bump`, { method: "POST" });
                if (!res.ok) throw new Error("Failed");
                toast({ title: t("detail.actions.bumpTriggered"), description: fullName });
              } catch {
                toast({ title: t("detail.actions.bumpFailed"), variant: "destructive" });
              }
            }}
            className="group inline-flex items-center h-9 pl-[9px] rounded-full border border-black/[0.125] text-foreground/60 hover:text-foreground text-[12px] font-medium overflow-hidden shrink-0 transition-[max-width,color,border-color] duration-200 max-w-9 hover:max-w-[140px]"
            title={t("detail.actions.triggerBump")}
          >
            <RotateCcw className="h-4 w-4 shrink-0" />
            <span className="whitespace-nowrap pl-1.5 pr-2.5 opacity-0 group-hover:opacity-100 transition-opacity duration-150">
              {t("detail.actions.bump")} {lead.current_bump_stage ? `${lead.current_bump_stage}/3` : ""}
            </span>
          </button>

          <button
            onClick={async () => {
              try {
                const res = await apiFetch(`/api/leads/${leadId}/reset-demo`, { method: "POST" });
                if (!res.ok) throw new Error("Failed");
                resetScoreToZero();
                toast({ title: t("detail.actions.leadReset"), description: fullName });
              } catch {
                toast({ title: t("detail.actions.resetFailed"), variant: "destructive" });
              }
            }}
            className="group inline-flex items-center h-9 pl-[9px] rounded-full border border-black/[0.125] text-foreground/60 hover:text-foreground text-[12px] font-medium overflow-hidden shrink-0 transition-[max-width,color,border-color] duration-200 max-w-9 hover:max-w-[110px]"
            title={t("detail.actions.resetLead")}
          >
            <Trash2 className="h-4 w-4 shrink-0" />
            <span className="whitespace-nowrap pl-1.5 pr-2.5 opacity-0 group-hover:opacity-100 transition-opacity duration-150">
              {t("detail.actions.resetLead")}
            </span>
          </button>

          <button
            onClick={async () => {
              try {
                const res = await apiFetch(`/api/leads/${leadId}/demo-reset-and-send`, { method: "POST" });
                if (!res.ok) throw new Error("Failed");
                resetScoreToZero();
                toast({ title: t("detail.actions.demoStarted"), description: fullName });
              } catch {
                toast({ title: t("detail.actions.demoFailed"), variant: "destructive" });
              }
            }}
            className="group inline-flex items-center h-9 pl-[9px] rounded-full border border-amber-400/60 text-amber-600 dark:text-amber-400 hover:border-amber-500 hover:text-amber-700 dark:hover:text-amber-300 text-[12px] font-medium overflow-hidden shrink-0 transition-[max-width,color,border-color] duration-200 max-w-9 hover:max-w-[120px]"
            title={t("detail.actions.demoResetTitle")}
          >
            <Zap className="h-4 w-4 shrink-0" />
            <span className="whitespace-nowrap pl-1.5 pr-2.5 opacity-0 group-hover:opacity-100 transition-opacity duration-150">
              {t("detail.actions.demoReset")}
            </span>
          </button>

          <button
            onClick={async () => {
              try {
                const res = await apiFetch(`/api/leads/${leadId}/ai-send`, { method: "POST" });
                if (!res.ok) throw new Error("Failed");
                toast({ title: t("detail.actions.aiSent"), description: fullName });
              } catch {
                toast({ title: t("detail.actions.aiFailed"), variant: "destructive" });
              }
            }}
            className="group inline-flex items-center h-9 pl-[9px] rounded-full border border-black/[0.125] text-foreground/60 hover:text-foreground text-[12px] font-medium overflow-hidden shrink-0 transition-[max-width,color,border-color] duration-200 max-w-9 hover:max-w-[110px]"
            title={t("detail.actions.aiSendMessage")}
          >
            <Bot className="h-4 w-4 shrink-0" />
            <span className="whitespace-nowrap pl-1.5 pr-2.5 opacity-0 group-hover:opacity-100 transition-opacity duration-150">
              {t("detail.actions.aiSend")}
            </span>
          </button>
        </div>

        {/* Scrollable body */}
        <div className="flex-1 overflow-y-auto px-4 py-4 md:px-5" data-testid="lead-detail-panel-body">

          {/* Contact Info — with inline editing */}
          <SectionTitle icon={<User className="h-3.5 w-3.5" />} title={t("detail.sections.contact")} />
          <div
            className="rounded-xl border border-border/40 bg-muted/20 px-3 py-1.5"
            data-testid="contact-info-section"
          >
            <InlineEditField
              label={t("detail.fields.name")}
              value={fullName}
              icon={<User className="h-3 w-3" />}
              onSave={async (v) => {
                if (!leadId) return;
                const parts = v.trim().split(/\s+/);
                const firstName = parts[0] || "";
                const lastName = parts.slice(1).join(" ") || "";
                await apiFetch(`/api/leads/${leadId}`, {
                  method: "PATCH",
                  headers: { "Content-Type": "application/json" },
                  body: JSON.stringify({ first_name: firstName, last_name: lastName }),
                });
              }}
              testId="inline-edit-name"
            />
            <InlineEditField
              label={t("detail.fields.phone")}
              value={lead.phone || ""}
              icon={<Phone className="h-3 w-3" />}
              type="tel"
              onSave={(v) => handleInlineFieldSave("phone", v)}
              testId="inline-edit-phone"
            />
            <InlineEditField
              label={t("detail.fields.email")}
              value={lead.email || ""}
              icon={<Mail className="h-3 w-3" />}
              type="email"
              onSave={(v) => handleInlineFieldSave("email", v)}
              testId="inline-edit-email"
            />
            <InlineEditField
              label={t("detail.fields.priority")}
              value={lead.priority || ""}
              icon={<Activity className="h-3 w-3" />}
              onSave={(v) => handleInlineFieldSave("priority", v)}
              selectOptions={["", "High", "Medium", "Low"]}
              testId="inline-edit-priority"
            />
            <InfoRow
              label={t("detail.fields.language")}
              value={lead.language}
            />
            <InfoRow
              label={t("detail.fields.source")}
              value={source}
            />
            {/* Campaign — editable dropdown (#31, agency view only) */}
            {isAgencyPanel && (
              <div
                className="flex items-center justify-between gap-3 py-1.5 border-b border-border/30 last:border-0 group"
                data-testid="inline-edit-campaign"
              >
                <div className="flex items-center gap-1.5 shrink-0">
                  <span className="text-muted-foreground/60"><Layers className="h-3 w-3" /></span>
                  <span className="text-[11px] text-muted-foreground">{t("detail.fields.campaign")}</span>
                </div>
                <select
                  value={String(lead.campaignsId ?? lead.campaigns_id ?? "")}
                  onChange={async (e) => {
                    const val = e.target.value;
                    await handleInlineFieldSave("campaignsId", val ? val : (null as any));
                  }}
                  className="text-[12px] bg-transparent border border-dashed border-border/60 rounded px-1.5 py-0.5 max-w-[160px] focus:outline-none focus:ring-1 focus:ring-brand-indigo/50 text-foreground hover:bg-muted/40 transition-colors cursor-pointer"
                  data-testid="inline-edit-campaign-select"
                >
                  <option value="">{"2014"}</option>
                  {campaigns.map((c) => (
                    <option key={c.id} value={c.id}>{c.name}</option>
                  ))}
                </select>
              </div>
            )}
          </div>

          {/* Status */}
          <SectionTitle icon={<Activity className="h-3.5 w-3.5" />} title={t("detail.sections.status")} />
          <div className="rounded-xl border border-border/40 bg-muted/20 px-3 py-1.5">
            {/* Pipeline Stage — interactive dropdown */}
            <div
              className="flex items-start justify-between gap-3 py-1.5 border-b border-border/30"
              data-testid="pipeline-stage-row"
            >
              <div className="flex items-center gap-1.5 shrink-0">
                <span className="text-[11px] text-muted-foreground">{t("detail.fields.pipelineStage")}</span>
              </div>
              <div className="flex items-center gap-1.5 flex-wrap justify-end">
                {/* Change dropdown */}
                <Select
                  value={convStatus}
                  onValueChange={handleStageChange}
                  disabled={savingStatus}
                >
                  <SelectTrigger
                    className="h-6 w-auto min-w-[70px] text-[11px] px-2 py-0 border-dashed border-border/60 bg-transparent hover:bg-muted/40 transition-colors"
                    data-testid="pipeline-stage-trigger"
                    aria-label={t("detail.fields.pipelineStage")}
                  >
                    <SelectValue placeholder={t("detail.fields.changePlaceholder")} />
                  </SelectTrigger>
                  <SelectContent data-testid="pipeline-stage-dropdown">
                    {PIPELINE_STAGES.map((stage) => {
                      const colors = STATUS_COLORS[stage] ?? { bg: "bg-muted", text: "text-muted-foreground" };
                      return (
                        <SelectItem
                          key={stage}
                          value={stage}
                          className="text-[12px]"
                          data-testid={`pipeline-stage-option-${stage.replace(/\s+/g, "-").toLowerCase()}`}
                        >
                          <span
                            className={cn(
                              "inline-flex items-center gap-1.5 px-1.5 py-0.5 rounded-full text-[11px] font-semibold",
                              colors.bg,
                              colors.text
                            )}
                          >
                            {stage}
                          </span>
                        </SelectItem>
                      );
                    })}
                  </SelectContent>
                </Select>

                {/* Saving/saved indicator */}
                {savingStatus && (
                  <Loader2
                    className="h-3 w-3 animate-spin text-muted-foreground"
                    data-testid="pipeline-stage-saving"
                  />
                )}
                {stageSaved && !savingStatus && (
                  <CheckCircle2
                    className="h-3.5 w-3.5 text-emerald-500"
                    data-testid="pipeline-stage-saved"
                  />
                )}
              </div>
            </div>

            <InfoRow label={t("detail.fields.automation")} value={autoStatus} />

            {/* Manual Takeover — toggle switch */}
            <div
              className="flex items-center justify-between gap-3 py-1.5 border-t border-border/30"
              data-testid="manual-takeover-row"
            >
              <div className="flex items-center gap-1.5 shrink-0">
                <span className="text-muted-foreground/60">
                  {localManualTakeover ? <UserX className="h-3 w-3" /> : <UserCheck className="h-3 w-3" />}
                </span>
                <span className="text-[11px] text-muted-foreground">{t("detail.fields.manualTakeover")}</span>
                {localManualTakeover && (
                  <span className="text-[10px] font-semibold text-amber-600 dark:text-amber-400 bg-amber-400/15 px-1.5 py-px rounded-full">
                    {t("detail.fields.aiPaused")}
                  </span>
                )}
              </div>
              <div className="flex items-center gap-1.5">
                {savingManualTakeover && <Loader2 className="h-3 w-3 animate-spin text-muted-foreground" />}
                <Switch
                  checked={localManualTakeover}
                  onCheckedChange={handleManualTakeoverChange}
                  disabled={savingManualTakeover}
                  data-testid="manual-takeover-toggle"
                  aria-label={t("detail.fields.manualTakeover")}
                />
              </div>
            </div>
          </div>

          {/* Lead Scores — arc + tier + detailed sub-score breakdown */}
          <>
            <SectionTitle icon={<BarChart2 className="h-3.5 w-3.5" />} title={t("detail.sections.scores")} />
            <div
              className="rounded-xl border border-border/40 bg-muted/20 px-4 py-4 flex flex-col gap-4 relative"
              data-testid="lead-score-gauges"
            >
              {/* Arc + trend row */}
              <div className="flex items-center gap-4">
                <div className="relative shrink-0">
                  <ScoreArcPanel score={panelScore} tier={scoreBreakdown?.tier} />
                  {/* Tier tag — top-right of score arc */}
                  {scoreBreakdown && (
                    <span
                      className={cn("absolute -top-1 -right-2 text-[10px] font-bold px-2 py-0.5 rounded-full z-10", TIER_COLORS[scoreBreakdown.tier] ?? TIER_COLORS.Sleeping)}
                      style={(scoreBreakdown.tier === "Hot" || scoreBreakdown.tier === "Awake") ? {
                        boxShadow: `0 0 8px 2px ${scoreBreakdown.tier === "Hot" ? "rgba(239,68,68,0.4)" : "rgba(16,185,129,0.4)"}`,
                      } : undefined}
                    >
                      {scoreBreakdown.tier}
                    </span>
                  )}
                </div>
                <div className="flex flex-col gap-1.5">
                  {scoreBreakdown && (
                    <div className="flex items-center gap-1.5 text-sm text-muted-foreground">
                      <TrendIcon
                        trend={scoreBreakdown.trend}
                        upClass="h-4 w-4 text-blue-500"
                        downClass="h-4 w-4 text-gray-400"
                      />
                      <span>{scoreBreakdown.trend === "up" ? "Trending up" : scoreBreakdown.trend === "down" ? "Trending down" : "Stable"}</span>
                    </div>
                  )}
                  {!scoreBreakdown && scoreLoading && (
                    <div className="flex flex-col gap-2">
                      <div className="h-5 w-20 bg-muted animate-pulse rounded-full" />
                      <div className="h-3 w-16 bg-muted animate-pulse rounded" />
                    </div>
                  )}
                </div>
              </div>

              {/* Sub-score bars with context — extra spacing */}
              {scoreBreakdown && (
                <div className="flex flex-col gap-5">
                  <ScoreDetailBar
                    label="Engagement"
                    rawScore={scoreBreakdown.engagement_score}
                    weight={1}
                    maxRaw={30}
                    context={engagementContext(lead)}
                  />
                  <ScoreDetailBar
                    label="Activity"
                    rawScore={scoreBreakdown.activity_score}
                    weight={1}
                    maxRaw={20}
                    context={activityContext(lead)}
                  />
                  <ScoreDetailBar
                    label="Funnel"
                    rawScore={scoreBreakdown.funnel_weight}
                    weight={1}
                    maxRaw={50}
                    context={funnelContext(lead)}
                  />
                </div>
              )}

              {/* Signal chips */}
              {scoreBreakdown && scoreBreakdown.signals.length > 0 && (
                <div className="flex flex-wrap gap-1.5">
                  {scoreBreakdown.signals.map((s) => (
                    <span key={s} className="text-[11px] px-2 py-0.5 rounded-full bg-muted text-muted-foreground border border-border/60">
                      {s}
                    </span>
                  ))}
                </div>
              )}
            </div>

            {/* AI Summary — below score gauges */}
            {lead.ai_memory && (() => {
              // Only show plain-text summaries here (not legacy JSON exchange logs)
              let isJsonArray = false;
              try {
                const parsed = JSON.parse(lead.ai_memory);
                if (Array.isArray(parsed)) isJsonArray = true;
              } catch { /* not JSON */ }
              if (isJsonArray) return null;
              return (
                <div
                  className="rounded-xl border border-border/40 bg-muted/20 px-3 py-2.5 mt-2"
                  data-testid="ai-summary-below-scores"
                >
                  <div className="flex items-center gap-1.5 mb-1.5">
                    <Bot className="h-3 w-3 text-muted-foreground/60" />
                    <span className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
                      {t("detail.fields.aiSummary", "AI Summary")}
                    </span>
                  </div>
                  <p className="text-[12px] text-foreground/80 leading-relaxed">{lead.ai_memory}</p>
                </div>
              );
            })()}
          </>

          {/* DNC / Opted-out Section */}
          <SectionTitle icon={<Ban className="h-3.5 w-3.5" />} title={t("detail.sections.doNotContact")} />
          <div
            className="rounded-xl border border-border/40 bg-muted/20 px-3 py-2"
            data-testid="dnc-section"
          >
            {/* Opted-out toggle */}
            <div
              className="flex items-center justify-between gap-3 py-1.5"
              data-testid="dnc-toggle-row"
            >
              <div className="flex items-center gap-1.5">
                <Ban className="h-3 w-3 text-muted-foreground/60" />
                <span className="text-[11px] text-muted-foreground">{t("detail.fields.optedOutDnc")}</span>
                {localOptedOut && (
                  <span className="text-[10px] font-semibold text-red-600 dark:text-red-400 bg-red-500/15 px-1.5 py-px rounded-full">
                    {t("detail.fields.dncActive")}
                  </span>
                )}
              </div>
              <div className="flex items-center gap-1.5">
                {savingDnc && <Loader2 className="h-3 w-3 animate-spin text-muted-foreground" />}
                {dncSaved && !savingDnc && <CheckCircle2 className="h-3 w-3 text-emerald-500" />}
                <Switch
                  checked={localOptedOut}
                  onCheckedChange={handleDncChange}
                  disabled={savingDnc}
                  data-testid="dnc-toggle"
                  aria-label={t("detail.fields.optedOutDnc")}
                />
              </div>
            </div>

            {/* DNC reason input — shows when opted out */}
            {showDncReason && (
              <div className="mt-1.5 pt-1.5 border-t border-border/30" data-testid="dnc-reason-container">
                <label className="text-[11px] text-muted-foreground mb-1 block">{t("detail.fields.dncReason")}</label>
                <div className="flex gap-1.5">
                  <input
                    type="text"
                    value={localDncReason}
                    onChange={(e) => setLocalDncReason(e.target.value)}
                    onBlur={handleDncReasonSave}
                    onKeyDown={(e) => { if (e.key === "Enter") handleDncReasonSave(); }}
                    placeholder={t("detail.fields.dncReasonPlaceholder")}
                    className="flex-1 text-[12px] bg-background border border-border/60 rounded px-2 py-1 focus:outline-none focus:ring-1 focus:ring-brand-indigo/50"
                    data-testid="dnc-reason-input"
                    disabled={savingDnc}
                  />
                </div>
                {localDncReason && (
                  <p className="mt-1 text-[11px] text-muted-foreground" data-testid="dnc-reason-display">
                    {t("detail.fields.dncReasonLabel")}: <span className="text-foreground/80">{localDncReason}</span>
                  </p>
                )}
              </div>
            )}
          </div>

          {/* Bump Stage Indicator */}
          {(lead.current_bump_stage != null || lead.bump_1_sent_at || lead.bump_2_sent_at || lead.bump_3_sent_at) && (
            <>
              <SectionTitle icon={<Layers className="h-3.5 w-3.5" />} title={t("detail.sections.bumpProgress")} />
              <div
                className="rounded-xl border border-border/40 bg-muted/20 px-3 py-3"
                data-testid="bump-stage-section"
              >
                {/* Stage progress bar */}
                <div className="flex items-center gap-1 mb-3">
                  {[1, 2, 3].map((stage) => {
                    const currentStage = Number(lead.current_bump_stage ?? 0);
                    const done = currentStage >= stage;
                    return (
                      <div
                        key={stage}
                        className={cn(
                          "flex-1 h-2 rounded-full transition-[width] duration-300",
                          done ? "bg-brand-indigo" : "bg-muted"
                        )}
                        data-testid={`bump-stage-step-${stage}`}
                        data-done={done ? "true" : "false"}
                      />
                    );
                  })}
                </div>

                {/* Current stage label */}
                <div className="flex items-center justify-between mb-2">
                  <span className="text-[11px] text-muted-foreground">{t("detail.fields.currentStage")}</span>
                  <span
                    className="text-[12px] font-semibold text-foreground tabular-nums"
                    data-testid="bump-current-stage"
                  >
                    {lead.current_bump_stage ?? 0} / 3
                  </span>
                </div>

                {/* Bump timestamps */}
                {lead.bump_1_sent_at && (
                  <div className="flex items-center justify-between py-0.5">
                    <span className="text-[11px] text-muted-foreground">{t("detail.fields.bump", { n: 1 })}</span>
                    <span className="text-[11px] text-foreground/80 tabular-nums" data-testid="bump-1-sent-at">
                      {fmtDateTime(lead.bump_1_sent_at)}
                    </span>
                  </div>
                )}
                {lead.bump_2_sent_at && (
                  <div className="flex items-center justify-between py-0.5">
                    <span className="text-[11px] text-muted-foreground">{t("detail.fields.bump", { n: 2 })}</span>
                    <span className="text-[11px] text-foreground/80 tabular-nums" data-testid="bump-2-sent-at">
                      {fmtDateTime(lead.bump_2_sent_at)}
                    </span>
                  </div>
                )}
                {lead.bump_3_sent_at && (
                  <div className="flex items-center justify-between py-0.5">
                    <span className="text-[11px] text-muted-foreground">{t("detail.fields.bump", { n: 3 })}</span>
                    <span className="text-[11px] text-foreground/80 tabular-nums" data-testid="bump-3-sent-at">
                      {fmtDateTime(lead.bump_3_sent_at)}
                    </span>
                  </div>
                )}
              </div>
            </>
          )}

          {/* Activity */}
          <SectionTitle icon={<MessageSquare className="h-3.5 w-3.5" />} title={t("detail.sections.activity")} />
          <div className="rounded-xl border border-border/40 bg-muted/20 px-3 py-1.5">
            <InfoRow label={t("detail.fields.leadCreated")} value={fmtDate(lead.created_at)} />
            <InfoRow label={t("detail.fields.lastUpdated")} value={fmtDateTime(lead.updated_at)} />
            <InfoRow label={t("detail.fields.lastInteraction")} value={fmtDateTime(lead.last_interaction_at)} />
            <InfoRow label={t("detail.fields.lastSent")} value={fmtDateTime(lead.last_message_sent_at)} />
            <InfoRow label={t("detail.fields.lastReceived")} value={fmtDateTime(lead.last_message_received_at)} />
            <InfoRow label={t("detail.fields.sentCount")} value={lead.message_count_sent} />
            <InfoRow label={t("detail.fields.receivedCount")} value={lead.message_count_received} />
            <InfoRow label={t("detail.fields.responseRate")} value={responseRate} />
            <InfoRow label={t("detail.fields.daysInactive")} value={daysInactive} />
            <InfoRow label={t("detail.fields.firstContacted")} value={fmtDate(lead.first_message_sent_at)} />
            <InfoRow label={t("detail.fields.nextAction")} value={fmtDateTime(lead.next_action_at)} />
            {lead.what_has_the_lead_done && (
              <InfoRow label={t("detail.fields.whatTheyDid")} value={lead.what_has_the_lead_done} />
            )}
          </div>

          {/* Booking */}
          {(lead.booked_call_date || lead.booking_confirmed_at) && (
            <>
              <SectionTitle icon={<PhoneCall className="h-3.5 w-3.5" />} title={t("detail.sections.booking")} />
              <div
                className="rounded-xl border border-border/40 bg-muted/20 px-3 py-1.5"
                data-testid="booked-call-section"
              >
                {lead.previous_booked_call_date && lead.re_scheduled_count != null && lead.re_scheduled_count > 0 && (
                  <div className="flex items-start justify-between gap-3 py-1.5 border-b border-border/30">
                    <span className="text-[11px] text-muted-foreground shrink-0">{t("detail.fields.previousCallDate", "Previous")}</span>
                    <span className="text-[12px] text-muted-foreground/50 line-through tabular-nums">{formatBookedDate(lead.previous_booked_call_date, accountTimezone)}</span>
                  </div>
                )}
                <InfoRow label={t("detail.fields.callDate")} value={formatBookedDate(lead.booked_call_date, accountTimezone)} />
                <InfoRow label={t("detail.fields.confirmedAt")} value={fmtDateTime(lead.booking_confirmed_at)} />
                {/* No-show indicator */}
                <div className="flex items-start justify-between gap-3 py-1.5 border-b border-border/30 last:border-0">
                  <span className="text-[11px] text-muted-foreground shrink-0">{t("detail.fields.noShow")}</span>
                  {lead.no_show ? (
                    <span
                      className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[11px] font-semibold bg-red-500/15 text-red-600 dark:text-red-400"
                      data-testid="no-show-badge"
                    >
                      <X className="h-3 w-3" />
                      {t("detail.fields.noShow")}
                    </span>
                  ) : (
                    <span className="text-[12px] text-muted-foreground">{"2014"}</span>
                  )}
                </div>
                {/* Reschedule count */}
                {lead.re_scheduled_count != null && lead.re_scheduled_count > 0 && (
                  <div className="flex items-center justify-between gap-3 py-1.5 border-b border-border/30 last:border-0">
                    <div className="flex items-center gap-1.5 shrink-0">
                      <RefreshCw className="h-3 w-3 text-muted-foreground/60" />
                      <span className="text-[11px] text-muted-foreground">{t("detail.fields.rescheduled")}</span>
                    </div>
                    <span
                      className="text-[12px] font-semibold text-amber-600 dark:text-amber-400 tabular-nums"
                      data-testid="reschedule-count"
                    >
                      {lead.re_scheduled_count}×
                    </span>
                  </div>
                )}
                {lead.call_duration_minutes != null && (
                  <InfoRow label={t("detail.fields.duration")} value={t("detail.fields.durationMinutes", { minutes: lead.call_duration_minutes })} />
                )}
                {/* Lead summary generated at booking */}
                {lead.ai_memory && (() => {
                  let isJsonArray = false;
                  try { if (Array.isArray(JSON.parse(lead.ai_memory))) isJsonArray = true; } catch { /* not JSON */ }
                  if (isJsonArray) return null;
                  return (
                    <div className="pt-2 pb-1 border-t border-border/30 mt-1">
                      <div className="flex items-center gap-1.5 mb-1">
                        <Bot className="h-3 w-3 text-muted-foreground/60" />
                        <span className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
                          {t("detail.fields.aiSummary", "AI Summary")}
                        </span>
                      </div>
                      <p className="text-[12px] text-foreground/80 leading-relaxed">{lead.ai_memory}</p>
                    </div>
                  );
                })()}
              </div>
            </>
          )}

          {/* AI Insights */}
          {(lead.ai_sentiment || lead.ai_memory || lead.ai_summary || localAiSummary) && (
            <>
              <SectionTitle icon={<Bot className="h-3.5 w-3.5" />} title={t("detail.sections.aiInsights")} />
              <div
                className="rounded-xl border border-border/40 bg-muted/20 px-3 py-1.5"
                data-testid="ai-insights-section"
              >
                {/* AI summary */}
                {(localAiSummary || lead.ai_summary) && (
                  <div className="py-1.5 border-b border-border/30">
                    <div className="text-[11px] text-muted-foreground mb-1">{t("detail.fields.aiSummary")}</div>
                    <p className="text-[12px] text-foreground/80 leading-relaxed">{localAiSummary || lead.ai_summary}</p>
                  </div>
                )}
                {/* Sentiment badge — color coded */}
                {lead.ai_sentiment && (
                  <div className="flex items-start justify-between gap-3 py-1.5 border-b border-border/30 last:border-0">
                    <span className="text-[11px] text-muted-foreground shrink-0">{t("detail.fields.aiSentiment")}</span>
                    <SentimentBadge sentiment={lead.ai_sentiment} />
                  </div>
                )}
                {/* AI memory — formatted readably */}
                {lead.ai_memory && (
                  <div className="py-1.5" data-testid="ai-memory-display">
                    <div className="text-[11px] text-muted-foreground mb-1.5">{t("detail.fields.aiMemory")}</div>
                    <pre className="text-[11px] text-foreground/80 leading-relaxed whitespace-pre-wrap font-sans break-words">
                      {formatAiMemory(lead.ai_memory)}
                    </pre>
                  </div>
                )}
              </div>
            </>
          )}

          {/* Notes — editable + voice memo + AI notes */}
          <div data-testid="lead-notes-section">
            <div className="flex items-center justify-between mb-2 mt-4">
              <div className="flex items-center gap-2">
                <span className="text-muted-foreground"><StickyNote className="h-3.5 w-3.5" /></span>
                <h3 className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">{t("detail.sections.notes")}</h3>
              </div>
              <div className="flex items-center gap-1.5">
                {/* Voice memo recording button */}
                {transcribing ? (
                  <div className="flex items-center gap-1.5 text-[10px] text-brand-indigo">
                    <Loader2 className="h-3 w-3 animate-spin" />
                    {t("notes.transcribing")}
                  </div>
                ) : isRecordingVoice ? (
                  <button
                    onClick={stopVoiceRecording}
                    className="flex items-center gap-1.5 h-9 px-3 rounded-full bg-red-500/15 text-red-600 text-[12px] font-medium border border-red-300/60 hover:bg-red-500/25 transition-colors"
                    title={t("notes.stopRecording")}
                  >
                    <Square className="h-3 w-3 fill-current" />
                    {recordingSeconds}s
                  </button>
                ) : (
                  <button
                    onClick={startVoiceRecording}
                    disabled={savingNotes || transcribing}
                    className="inline-flex items-center justify-center h-9 w-9 rounded-full border border-black/[0.125] text-muted-foreground hover:text-foreground hover:border-black/[0.175] transition-colors disabled:opacity-50"
                    title={t("notes.recordVoiceMemo")}
                  >
                    <Mic className="h-4 w-4" />
                  </button>
                )}
                {/* Save indicators */}
                {savingNotes && (
                  <Loader2
                    className="h-3 w-3 animate-spin text-muted-foreground"
                    data-testid="notes-saving-indicator"
                  />
                )}
                {notesSaved && !savingNotes && (
                  <span className="flex items-center gap-1 text-[10px] text-emerald-600 dark:text-emerald-400" data-testid="notes-saved-indicator">
                    <CheckCircle2 className="h-3 w-3" />
                    {t("notes.saved")}
                  </span>
                )}
                {notesDirty && !savingNotes && (
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={handleNotesSave}
                    className="h-6 px-2 text-[11px] gap-1"
                    data-testid="notes-save-button"
                    aria-label={t("notes.saveNotes")}
                  >
                    <Save className="h-3 w-3" />
                    {t("notes.save")}
                  </Button>
                )}
              </div>
            </div>
            <div className="rounded-xl border border-border/40 bg-muted/20 p-2">
              <Textarea
                value={localNotes}
                onChange={(e) => {
                  setLocalNotes(e.target.value);
                  setNotesDirty(e.target.value !== notesOriginalRef.current);
                  setNotesSaved(false);
                }}
                onBlur={handleNotesSave}
                placeholder={t("notes.placeholder")}
                className="min-h-[80px] resize-none text-[12px] bg-transparent border-0 shadow-none focus-visible:ring-0 p-1 leading-relaxed"
                data-testid="lead-notes-textarea"
                disabled={savingNotes || transcribing}
              />
            </div>

          </div>

          {/* Tags */}
          <SectionTitle icon={<Tag className="h-3.5 w-3.5" />} title={t("detail.sections.tags")} />
          <div
            className="rounded-xl border border-border/40 bg-muted/20 px-3 py-3"
            data-testid="lead-detail-tags-section"
          >
            {loadingTags ? (
              <div className="flex items-center gap-2 text-[12px] text-muted-foreground">
                <Loader2 className="h-3.5 w-3.5 animate-spin" />
                {t("tags.loadingTags")}
              </div>
            ) : (
              <div className="flex flex-wrap gap-1.5" data-testid="lead-tags-chips">
                {/* Existing tag chips */}
                {leadTags.map((tag) => (
                  <span
                    key={tag.id}
                    className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[11px] font-semibold bg-violet-500/15 text-violet-700 dark:text-violet-300 ring-1 ring-violet-500/20"
                    data-testid={`lead-tag-chip-${tag.id}`}
                    data-tag-id={tag.id}
                    data-tag-name={tag.name}
                  >
                    <Tag className="h-2.5 w-2.5 shrink-0" />
                    {tag.name}
                    <button
                      type="button"
                      onClick={() => handleRemoveTag(tag.id)}
                      disabled={removingTagId === tag.id}
                      className="ml-0.5 rounded-full hover:bg-violet-500/20 transition-colors disabled:opacity-50"
                      aria-label={t("tags.removeTag", { name: tag.name })}
                      data-testid={`lead-tag-remove-${tag.id}`}
                    >
                      {removingTagId === tag.id
                        ? <Loader2 className="h-2.5 w-2.5 animate-spin" />
                        : <X className="h-2.5 w-2.5" />
                      }
                    </button>
                  </span>
                ))}

                {/* Add tag button + dropdown */}
                <div className="relative">
                  <button
                    type="button"
                    onClick={() => setShowTagDropdown((v) => !v)}
                    disabled={addingTag}
                    className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[11px] font-medium border border-dashed border-black/[0.125] text-muted-foreground hover:text-foreground hover:border-black/[0.175] transition-colors disabled:opacity-50"
                    data-testid="lead-tag-add-button"
                    aria-label={t("tags.addTag")}
                  >
                    {addingTag
                      ? <Loader2 className="h-2.5 w-2.5 animate-spin" />
                      : <Plus className="h-2.5 w-2.5" />
                    }
                    {t("tags.addTag")}
                  </button>

                  {/* Tag selection dropdown */}
                  {showTagDropdown && (
                    <div
                      className="absolute left-0 top-7 z-50 min-w-[160px] max-w-[calc(100vw-2rem)] max-h-[200px] overflow-y-auto rounded-xl border border-border bg-popover shadow-lg py-1"
                      data-testid="lead-tag-dropdown"
                    >
                      {unassignedTags.length === 0 ? (
                        <div className="px-3 py-2 text-[12px] text-muted-foreground">
                          {availableTags.length === 0 ? t("tags.noTagsAvailable") : t("tags.allTagsAssigned")}
                        </div>
                      ) : (
                        unassignedTags.map((tag) => (
                          <button
                            key={tag.id}
                            type="button"
                            onClick={() => handleAddTag(tag)}
                            className="w-full flex items-center gap-2 px-3 py-1.5 text-[12px] text-left hover:bg-muted/50 transition-colors"
                            data-testid={`lead-tag-option-${tag.id}`}
                          >
                            <Tag className="h-3 w-3 shrink-0 text-muted-foreground" />
                            <span className="truncate">{tag.name}</span>
                            {tag.category && (
                              <span className="ml-auto text-[10px] text-muted-foreground shrink-0">{tag.category}</span>
                            )}
                          </button>
                        ))
                      )}
                    </div>
                  )}
                </div>

                {leadTags.length === 0 && !showTagDropdown && (
                  <span className="text-[12px] text-muted-foreground italic">{t("tags.noTagsAssigned")}</span>
                )}
              </div>
            )}
          </div>

          {/* Interaction Timeline */}
          <SectionTitle
            icon={<MessageSquare className="h-3.5 w-3.5" />}
            title={interactions.length > 0 ? t("timeline.titleWithCount", { count: interactions.length }) : t("timeline.title")}
          />
          <div
            data-testid="lead-detail-panel-interactions"
          >
            {loadingInteractions ? (
              <div className="space-y-1">
                {Array.from({ length: 4 }).map((_, i) => (
                  <div key={i} className="flex items-start gap-2.5 bg-white/90 dark:bg-card/90 rounded-xl px-2 py-1.5">
                    <div className="h-7 w-7 rounded-lg bg-muted animate-pulse shrink-0" />
                    <div className="flex-1 min-w-0 space-y-1.5 pt-0.5">
                      <div className="h-3.5 w-3/5 bg-muted animate-pulse rounded" />
                      <div className="h-3 w-4/5 bg-muted animate-pulse rounded" />
                    </div>
                  </div>
                ))}
              </div>
            ) : interactions.length === 0 ? (
              <div className="flex flex-col items-center justify-center text-center py-8 px-4">
                <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-muted mb-2">
                  <MessageSquare className="h-4 w-4 text-muted-foreground" />
                </div>
                <p className="text-sm font-medium text-foreground">{t("timeline.noInteractions")}</p>
                <p className="text-xs text-muted-foreground max-w-[240px] mt-1">
                  {t("timeline.noInteractionsHint")}
                </p>
              </div>
            ) : (
              <div
                className="max-h-[320px] overflow-y-auto space-y-1"
                data-testid="interaction-timeline"
              >
                {(() => {
                  // Status names that get a colored status chip instead of a tag chip
                  const STATUS_TAG_NAMES = new Set(["Contacted","Responded","Multiple Responses","Qualified","Booked","Lost","DND","Opted Out","DNC"]);
                  const STATUS_HEX: Record<string, string> = { Contacted:"#818CF8", Responded:"#3ACBDF", "Multiple Responses":"#31D35C", Qualified:"#AED62E", Booked:"#22C55E", Lost:"#DC2626", DND:"#722F37", "Opted Out":"#6B7280", DNC:"#6B7280" };
                  // Case-insensitive lookup
                  const _sLower = new Map<string, string>();
                  Array.from(STATUS_TAG_NAMES).forEach(s => _sLower.set(s.toLowerCase(), s));
                  const findCanonical = (n: string) => STATUS_TAG_NAMES.has(n) ? n : (_sLower.get(n.toLowerCase()) ?? null);
                  const TAG_HEX: Record<string, string> = { red:"#EF4444", orange:"#F97316", yellow:"#EAB308", green:"#22C55E", blue:"#3B82F6", indigo:"#6366F1", purple:"#A855F7", pink:"#EC4899", gray:"#6B7280" };

                  type TLItem =
                    | { kind: "msg"; data: Interaction; ts: string }
                    | { kind: "tag"; tagName: string; tagColor: string; timeStr: string; eventType: string; ts: string }
                    | { kind: "status"; statusName: string; timeStr: string; hex: string; ts: string };

                  // Synthetic status events from interaction patterns
                  const existingLower = new Set(tagEvents.map((te: any) => (te.tag_name || "").toLowerCase()));
                  const synthEvents: any[] = [];
                  let inboundN = 0;
                  for (const m of interactions) {
                    if ((m.direction || "").toLowerCase() !== "outbound") {
                      inboundN++;
                      if (inboundN === 1 && !existingLower.has("responded")) {
                        synthEvents.push({ tag_name: "Responded", tag_color: "", created_at: m.created_at ?? (m as any).createdAt, event_type: "added" });
                      }
                      if (inboundN === 2 && !existingLower.has("multiple responses") && !existingLower.has("multiple messages")) {
                        synthEvents.push({ tag_name: "Multiple Responses", tag_color: "", created_at: m.created_at ?? (m as any).createdAt, event_type: "added" });
                      }
                    }
                  }
                  const allTE = [...tagEvents, ...synthEvents];

                  const items: TLItem[] = [
                    ...interactions.map(m => ({ kind: "msg" as const, data: m, ts: m.created_at ?? (m as any).createdAt ?? "" })),
                    ...allTE.map(te => {
                      const ts = te.created_at ?? "";
                      const timeStr = ts ? new Date(ts).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) : "";
                      const canonical = findCanonical(te.tag_name);
                      if (canonical && te.event_type !== "removed") {
                        return { kind: "status" as const, statusName: canonical, timeStr, hex: STATUS_HEX[canonical] ?? "#6B7280", ts };
                      }
                      return { kind: "tag" as const, tagName: te.tag_name, tagColor: te.tag_color ?? "gray", timeStr, eventType: te.event_type, ts };
                    }),
                  ].sort((a, b) => a.ts.localeCompare(b.ts));

                  return items.map((item, idx) => {
                    if (item.kind === "status") {
                      return (
                        <div key={`status-${idx}`} className="flex justify-center py-1">
                          <span className="inline-flex items-center gap-1.5 text-[11px] font-medium rounded-full px-3 py-1 bg-white dark:bg-gray-900 shadow-sm select-none" style={{ color: item.hex }}>
                            <Activity className="w-3 h-3" style={{ color: item.hex }} />
                            {item.statusName}
                            {item.timeStr && <span className="opacity-50">· {item.timeStr}</span>}
                          </span>
                        </div>
                      );
                    }
                    if (item.kind === "tag") {
                      const isRemoved = item.eventType === "removed";
                      const hex = TAG_HEX[item.tagColor] ?? "#6B7280";
                      return (
                        <div key={`tag-${idx}`} className={cn("flex justify-center py-1", isRemoved && "opacity-50")}>
                          <span className="inline-flex items-center gap-1.5 text-[11px] font-medium rounded-full px-3 py-1 bg-white dark:bg-gray-900 shadow-sm select-none" style={{ color: hex }}>
                            <Tag className="w-3 h-3" style={{ color: hex }} />
                            <span className={cn(isRemoved && "line-through")}>{item.tagName}</span>
                            {item.timeStr && <span className="opacity-50">· {item.timeStr}</span>}
                          </span>
                        </div>
                      );
                    }
                    // msg item
                    const m = item.data;
                    const outbound = String(m.direction || "").toLowerCase() === "outbound";
                    const AI_TB = new Set(["ai_conversation", "campaign_launcher", "bump_scheduler",
                      "manual_bump_trigger", "inbound_handler", "booking_webhook", "booking_confirmation"]);
                    const isAI = Boolean(m.ai_generated || m.aiGenerated)
                      || Boolean(m.is_bump || m.isBump)
                      || AI_TB.has(((m as any).triggered_by ?? (m as any).triggeredBy ?? "").toLowerCase());
                    const isHuman = Boolean(m.is_manual_follow_up);
                    const isBump = Boolean(m.is_bump);
                    const msgContent = m.Content || m.content || "";
                    const who = m.Who || m.who || "";
                    const iconCfg = isAI
                      ? { icon: Bot, color: "text-violet-600", bg: "bg-violet-50 dark:bg-violet-500/10" }
                      : isHuman && outbound
                        ? { icon: User, color: "text-orange-600", bg: "bg-orange-50 dark:bg-orange-500/10" }
                        : outbound
                          ? { icon: Send, color: "text-brand-indigo", bg: "bg-brand-indigo/10" }
                          : { icon: MessageSquare, color: "text-emerald-600", bg: "bg-emerald-50 dark:bg-emerald-500/10" };
                    const IconComp = iconCfg.icon;
                    return (
                      <div
                        key={m.id}
                        className="flex items-start gap-2.5 bg-white/90 dark:bg-card/90 rounded-xl px-2 py-1.5 transition-colors hover:bg-white dark:hover:bg-card"
                        data-testid={`lead-detail-interaction-${m.id}`}
                        data-index={idx}
                        data-direction={m.direction}
                        data-ai-generated={isAI ? "true" : "false"}
                      >
                        <div className={cn("shrink-0 flex items-center justify-center rounded-lg h-7 w-7", iconCfg.bg)}>
                          <IconComp className={cn("h-4 w-4", iconCfg.color)} />
                        </div>
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center gap-1.5">
                            <p className="text-[12px] font-medium text-foreground leading-snug truncate">
                              {outbound ? (isAI ? t("timeline.aiSent") : isHuman ? t("timeline.agentSent") : t("timeline.sent")) : t("timeline.received")}
                              {isBump && <span className="text-amber-600 dark:text-amber-400 ml-1">· {t("timeline.bump")}</span>}
                              {m.type && m.type !== "SMS" && (
                                <span className="text-muted-foreground/70 ml-1">· {m.type}</span>
                              )}
                            </p>
                          </div>
                          <p className="text-[11px] text-muted-foreground truncate mt-0.5">
                            {msgContent || <span className="italic">{"2014"}</span>}
                          </p>
                          {who && (
                            <p className="text-[10px] text-muted-foreground/60 mt-0.5">{t("timeline.via", { who })}</p>
                          )}
                        </div>
                        <span
                          className="text-[10px] text-muted-foreground tabular-nums shrink-0 mt-0.5"
                          data-testid={`interaction-timestamp-${m.id}`}
                        >
                          {fmtDateTime(m.created_at)}
                        </span>
                      </div>
                    );
                  });
                })()}
              </div>
            )}
          </div>

          {/* Campaign / Account */}
          <SectionTitle icon={<Tag className="h-3.5 w-3.5" />} title={t("detailView.assignment")} />
          <div className="rounded-xl border border-border/40 bg-muted/20 px-3 py-1.5 mb-6">
            <InfoRow label={t("detail.fields.account")} value={lead.Account || lead.account_id} />
            <InfoRow label={t("detailView.campaign")} value={lead.Campaign || lead.campaign_id} />
            <InfoRow label={t("contact.created")} value={fmtDate(lead.created_at)} />
            {convStatus && (
              <div className="flex items-start justify-between gap-3 py-1.5 border-b border-border/30 last:border-0">
                <span className="text-[11px] text-muted-foreground shrink-0">{t("detail.sections.status")}</span>
                <StatusBadge label={convStatus} />
              </div>
            )}
            {priority && (
              <div className="flex items-start justify-between gap-3 py-1.5 border-b border-border/30 last:border-0">
                <span className="text-[11px] text-muted-foreground shrink-0">{t("detail.fields.priority")}</span>
                <PriorityBadge priority={priority} />
              </div>
            )}
          </div>
        </div>
      </SheetContent>
    </Sheet>
  );
}
